### ISSUE TITLE
Small caps "L" not recognized .

### ISSUE THREAD

**Issue by OmarBoshra** [googlesamples/mlkit#110]
Small caps "l"  isn't  recognized by itself in mlkit .

![video-to-gif-converter](https://user-images.githubusercontent.com/47230931/90550950-f2025200-e190-11ea-85ae-d1af2be61f84.gif)

**Comment by calren** [comment]
Interesting! I believe this is because the lowercased 'l' by itself just looks like a line. If this lower cased 'l' was part of a word, on the other hand, I believe the api would be able to recognize it. 

We don't have plans to support recognizing 'l' by itself, as that doesn't seem like a common use case, so I'm going to go ahead and close this for now. 

Thanks for putting this on our radar! If anything changes in our plans, we'll be sure to update this issue.

**Comment by OmarBoshra** [comment]
Actually they are different in various fonts for example "I" &  "l"  .So at least the API can detect that difference .

**Comment by OmarBoshra** [comment]
Actually for the various font types  small "l" is different and is either detected as 1 or not detected ,the "I" capital is detected only when it has 2 lines top and bottom.
