### ISSUE TITLE
Find dimensions of body

### ISSUE THREAD

**Issue by gulamjilani61973** [googlesamples/mlkit#132]
Can we find dimensions of our body using pise detect. Like what is my waist and chest size and other body part measurements

**Comment by steven-chengji-yan** [comment]
This is not directly provided by the Pose Detection API. It would be hard to get accurate measurement, because:
1. the pose API doesn't depend on/require depth information, so X pixels on screen could mean different real distance depending on how far the person is.
2. even we have depth information, we only know how far the front surface of a person's body is, but don't know how far the person's back is.

You might be able to do some very very rough estimations by using some reference depending on your use case. For example, you might suggest the users to stand up-right to the camera and assume most people's left eye and right eye have the same distance and use it to infer the real distance of other body part. This still won't address the front/back body surface issue, so need some estimation there as well.
