### ISSUE TITLE
ML Face detection - FaceGraphic draws contours / box off the actual face position in cameraX activity and live viewport enabled

### ISSUE THREAD

**Issue by Jbwzx** [googlesamples/mlkit#138]
![disabled](https://user-images.githubusercontent.com/22195635/92941583-7bcbd500-f448-11ea-8fbc-0b0190eafefa.jpg)
![enabled](https://user-images.githubusercontent.com/22195635/92941598-7ff7f280-f448-11ea-9f63-0883fb81a04c.jpg)

**How to replicate:**
1. CameraXLivePreviewActivity
2. Face tracking
3. Settings -> Enable live viewport

Anyone knows what happens there? Does not happen in LivePreviewActivity

**Comment by steven-chengji-yan** [comment]
Hi Jbwzx,

I tried the latest sample app on my Pixel 1 with Android 10 and cannot reproduce the issue.

Could you provide more information, e.g. :
(1) Do you see the same issue in CameraX preview, if you disable live view port?
(2) Did you make any changes in the sample app?
(3) What device and OS are you using?

**Comment by Jbwzx** [comment]
@steven-chengji-yan 
Hi. Thanks for response. Sorry I should've put more info. 
1. No, without live viewport everything is work as expected (apart from fps being around 8-10, but thats understandable as we drop frames and pass current frame as Bitmap and wait)
2. No, clean build of master branch
3. So at first, I assumed it replicates on all devices, but after running app on more devices, I noticed a difference:
I tested on:
- Pixel (Works correctly)
- Samsung s10+ (Can replicate)
- Huawei p20 Lite (Can replicate)
- HTC One M9 (Can replicate)

I think it's something to do with CameraX target analysis resolution setting:
When I set target to 1000x1000 in settings on all devices they are different in InputImage size:
- HTC - 1088x1088
- s10+ - 1072x1072
- Huawei - 720x720
- Pixel (working case) - 1080x1440 

Thanks.

**Comment by steven-chengji-yan** [comment]
For CameraX API, we can only specify the target resolution. The real resolution is determined by CameraX. This is working as intended.

My understanding for the issue is that somehow, the CameraX preview and CameraX analysis use case are getting images with different aspect ratio, thus when trying to centerCrop, they might not align.

Could you try the following and let me know if it fix the issue?
Currently when creating the analysis use case, we [set the target resolution](https://github.com/googlesamples/mlkit/blob/e949654bef09e97b237c7692349c52ee06e9fd9e/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/CameraXLivePreviewActivity.java#L394-L397).
Could you try to set the preview to have the same resolution [here](https://github.com/googlesamples/mlkit/blob/e949654bef09e97b237c7692349c52ee06e9fd9e/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/CameraXLivePreviewActivity.java#L307), by using setTargetResolution API.

**Comment by Jbwzx** [comment]
Hi again @steven-chengji-yan 
Setting target resolution to preview did the trick!

Thank you very much for help, much appreciated.
