### ISSUE TITLE
Barcode Scanner on Android throws "Image already closed" exception

### ISSUE THREAD

**Issue by kaanozkaya** [googlesamples/mlkit#144]
This problem ocurred after I migrated to com.google.android.gms namespaced version of the library.
I'm using CameraX library and ImageAnalysis use case. I get mediaImage from the ImageProxy item that analyze method of ImageAnalyzer gives me, create an InputImage with that, and pass that to the BarcodeScanner object. I close the ImageProxy after creating the InputImage, but when I call the process method of my BarcodeScanner object, the task fails with the exception "Image already closed". I'm sure this shouldn't happen because I use the old Firebase version of the MlKit library in another project and it works fine with the same method I explained here.

**Comment by steven-chengji-yan** [comment]
There is a note in the dev doc about CameraX usage: https://developers.google.com/ml-kit/vision/barcode-scanning/android#4.-process-the-image

"
Note: If you are using the CameraX API, make sure to close the ImageProxy when finish using it, e.g., by adding an OnCompleteListener to the Task returned from the process method. See the [VisionProcessorBase](https://github.com/googlesamples/mlkit/blob/e949654bef09e97b237c7692349c52ee06e9fd9e/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/VisionProcessorBase.java#L178-L181) class in the quickstart sample app for an example.
"

In your case, you closed it too early, so got that error.

I guess the reason why Firebase version work is because at that time, ML Kit don't support YUV_420_888 format from CameraX directly, so when constructing the InputImage, it is copied and converted to another format directly. In this case, closing the original Image after that is fine.   However, that conversion takes time, so the construction of InputImage will block.   The current ML Kit defers the conversion to a later place, and also some features now support YUV_420_888 directly thus such conversion is not needed any more.  In this case, you should only close it after process is done.

**Comment by kaanozkaya** [comment]
Thanks for the explanation. It's stated in the InputImage.fromMediaImage method documentation that "After you get back an InputImage, it's safe to close the input Image.", maybe it would be better to clarify that statement.

**Comment by steven-chengji-yan** [comment]
Thanks for letting us know. Will fix the javadoc in next release.
