### ISSUE TITLE
[WORKAROUND] take photo of the face image inside the bounding box of face detection?

### ISSUE THREAD

**Issue by handhikadj** [googlesamples/mlkit#151]
i want to take photo of it without the embellishment (dots, etc)
how do I do it?

**Comment by steven-chengji-yan** [comment]
Hi handhikadj,

For the quickstart app, you can disable the drawing logic in the FaceGraphic class ([java](https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/facedetector/FaceGraphic.java), [kotlin](https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/kotlin/facedetector/FaceGraphic.kt))

========================================

About the taking photo part, it would probably be easier to write your own app for just that purpose, instead of modifying the code sample. The following are some pointers:

// If you are using bitmap to construct your InputImage
Bitmap bitmap = ...;
InputImage image = InputImage.fromBitmap(bitmap, 0);
faceDetector.process(image).addOnSuccessListener(
   results -> {
     // get the face bounding box from results
     // use the bounding box to crop bitmap to get the face bitmap
});

// For image source other than Bitmap, you probably need to do some extra conversion. You can probably find how to do those in StackOverflow.    e.g. "How to crop a ByteBuffer"
