### ISSUE TITLE
Annoying warning on supported colorspace format when running vision showcase on iOS

### ISSUE THREAD

**Issue by Silvercast** [googlesamples/mlkit#161]
I get the following warning out of the box when running the sample code.

`[WARNING]The specified colorspace format is not supported. Falling back on Libyuv.`

Latest code commit hash 08c3e1fbe66b06d6d6daed1a3c61e26aad2f512d.
XCode 12.0.1
iPhone 11

From what I see it happens when invoking `[detector resultsInImage:error:]` . The same warning on my other personal projects. I saw a suggestion for fix in StackOverflow conversation [here](https://stackoverflow.com/questions/62872667/the-specified-colorspace-format-is-not-supported-falling-back-on-libyuv#comment113346910_62872667) . However I think converting back and forth would slow the performance down.

**Comment by fbernaly** [comment]
I am getting the same when using ML Kit in iOS:

`The specified colorspace format is not supported. Falling back on Libyuv.`

What is the fix for this issue? Why is it close?

**Comment by bcdj** [comment]
Not fixed.  It's not closed.

**Comment by bcdj** [comment]
This will be fixed in our next release in January 2022.

**Comment by yunishim** [comment]
Hi bcdj,
Let me make sure my case, I just updated up-to-date MLKit libs(Dec, 14th, 2021).
Then, the sample doesn't print the warning log for both DEBUG and RELEASE build.
Is this behavior correct? I bet it is supposed to be printed in DEBUG as you mentioned.

Do you mean you will fix the sample code(not MLkit libs) in January 2022?
Thank you

**Comment by bcdj** [comment]
As I mentioned in my last comment, it will be fixed in our next release in 2022 (exact time TBD), so the current ML Kit release (Dec, 14th, 2021) doesn't have the fix yet.  If the sample doesn't print the warning log, it means the input image format does not trigger the logic producing those warning. In another word, the input image is using a supported colorspace format and the code does not have to fall back on Libyuv.

**Comment by AlexV525** [comment]
Could we have more documentation or flag control on this? More specifically:
- Address how to use a correct colorspace. For example, I'm using the `TextRecognizer v2` on iOS and following the document at https://developers.google.com/ml-kit/vision/text-recognition/v2/ios, which doesn't provide any information related.
- A flag/predicate to control whether this warning should be sent.

**Comment by bcdj** [comment]
The warning "The specified colorspace format is not supported. Falling back on Libyuv" is misleading. ML Kit supports all colorspace formats. It's just that different colorspace formats are handled in different ways. What the warning is trying to indicate is that some colorspace formats cannot be handled in one way, but will be handled in another way (Libyuv).  The warning is not useful to the developers, since they don't need to do anything special on their side, so we will remove the warning entirely in our next release.

**Comment by hardikvij195** [comment]
this issue is still not resolved on latest google_ml_kit: ^0.7.3

**Comment by bcdj** [comment]
The fix is not yet released. It's scheduled to become available around 02/22/22.

**Comment by bcdj** [comment]
Also, I assume that by "google_ml_kit: ^0.7.3", you meant the "google_ml_kit" flutter package?  If so, that package is not owned, endorsed, or supported by Google (including the ML Kit team), so I'm not sure about it.
