### ISSUE TITLE
Android FaceDetector.Face Euler angles are 0 all the time

### ISSUE THREAD

**Issue by zokirbekov** [googlesamples/mlkit#179]
I use this FaceDetectorOptions :

```
FaceDetectorOptions.Builder()
        .setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_FAST)
        .setClassificationMode(FaceDetectorOptions.CLASSIFICATION_MODE_ALL)
        .setLandmarkMode(FaceDetectorOptions.LANDMARK_MODE_ALL)
        .setExecutor(ActivityCompat.getMainExecutor(context))
        .build() 
```

but angles are 0

Sample also doesn't work

**Comment by andriy-tsvikla** [comment]
Try to add  
.setContourMode(FaceDetectorOptions.CONTOUR_MODE_ALL)

**Comment by swiyu** [comment]
Could you clarify which dependencies are you using? Do you depend on "play-services-mlkit-face-detection" or "com.google.mlkit:face-detection"? And what versions are you using? that would helpful for us to investigate.

**Comment by cs-googler** [comment]
Hi, if you are testing with sample app, modyfying the options in the code doesn't work since the app's setting will override it. The default setting with the sample app doesn't generate this result. You can click the setting button on the top right corner of the live preview activity -> scroll down to the face detection settings and set these options there.
