### ISSUE TITLE
Request for  Swift Package Manager  support

### ISSUE THREAD

**Issue by yujinqiu** [googlesamples/mlkit#180]

**Comment by stepan-votava** [comment]
Is there any news with SPM support? We have problems on M1 macs

**Comment by kristohear** [comment]
While Firebase is getting closer and closer to have full SPM support, is there any estimates on this one? It's a huge blocker for M1 macbooks.

**Comment by nilsnilsnils** [comment]
We need SPM support !

**Comment by AngryDuckFTW** [comment]
+1 for SPM

**Comment by kristohear** [comment]
@nilsnilsnils @AngryDuckFTW there is a topic here https://issuetracker.google.com/issues/174418229 , about MLKit SPM support, I think this repository is not checked as actively as this issuetracker topic there.

**Comment by yujinqiu** [comment]
1 year has passed  and M1 Pro/Max have released, but SPM is still on the way. :-(

**Comment by fukemy** [comment]
does it support now?>>

**Comment by bcdj** [comment]
Due to necessary internal infra is still being developed, we cannot add the SPM support yet.

**Comment by alexis-ag** [comment]
+1

**Comment by bcdj** [comment]
Hi everyone (@yujinqiu @stepan-votava @kristohear @nilsnilsnils @AngryDuckFTW @fukemy @alexis-ag): To help us gauge the importance of supporting Swift Package Manager, could you share the size of your user base? And if you can also provide an App Store link to your app, that would be helpful too. In addition, are you able to use Cocoapods version of ML Kit in place of Swift Package Manager when building your app? Will the lack of Swift Package Manager support block your development entirely?

**Comment by Frankatvend** [comment]
+1.  We intentionally moved away from Cocoapods to SPM two years ago in our project, I'm sad to hear that this great lib doesn't support SPM while looking for candidates.

**Comment by codeslaw** [comment]
@bcdj SPM is the currently recommended, and future-dominant method of managing dependencies. It's first-party and relatively mature. It seems inevitable that MLKit will need to migrate, and by waiting you discourage adoption in new projects (mixing dep. management is messy and occasionally quite frustrating)

So non-blocking, but high-misery. 

Current userbase: 50-100k mau, SPM app https://greg.app/
Previous userbase: Tinder, 50-100m mau, recently (2021) migrated SPM app

**Comment by garriguv** [comment]
Not supporting SPM and M1 machines is preventing us from adopting this package in our app. We'll likely work with other partners to provide the capability we're missing.

Obviously this is free so I understand if it's not a priority, but we'd love to use it.

The usage would be for internal, non-public facing apps. So low userbase, but business critical.

**Comment by lee-jongwoo** [comment]
@bcdj
Here's some information I hope will help:

1. App currently in development; No user base available
2. The CocoaPods version of ML Kit is available. `pod install` works, but the compiler throws a bunch of errors when building for simulator. I'll attach them below.
3. Building works when building for a real device, so it doesn't block development entirely. But this is still a major flaw since everything needs to be run on the device. Xcode features including Live Preview do not work.

Apple Silicon is the future of all macs. Many developers are migrating to M1 macs thanks to their performance and power efficiency. Now that the transition to Apple Silicon is almost done, ML Kit will have to migrate to SPM soon.

These are the errors:
<img width="656" alt="Screen Shot 2022-04-13 at 8 27 23 PM" src="https://user-images.githubusercontent.com/70620386/163170380-047dabc6-ea3c-425b-89ee-ffb584292e66.png">

**Comment by anatoliykant** [comment]
Can you please tell me if you have a timeline or roadmap to release xcframework for this great library?
Our team is waiting for you.
If you need help, then let me know.

**Comment by d-date** [comment]
I have successfully created MLKit's XCFramework using CocoaPods build artifacts and resolved the dependencies.
https://github.com/d-date/google-mlkit-swiftpm

However, I am unable to run it on iOS devices due to Dynamic Framework or code signing issues.
If anyone has a solution, please send me a pull request.

For MLKit team, please distribute your frameworks in ARM Mac (M1/M2) first to include arm64 iphonesimulator as Firebase team done.

**Comment by d-date** [comment]
> However, I am unable to run it on iOS devices due to Dynamic Framework or code signing issues.
If anyone has a solution, please send me a pull request.

Resolved! Now you can use MLKit in SwiftPM!

**Comment by d-date** [comment]
Unfortunately, I found some missing internal APIs. If you know about it, please let me know where is located.
https://github.com/d-date/google-mlkit-swiftpm/issues/16

**Comment by d-date** [comment]
> Unfortunately, I found some missing internal APIs. If you know about it, please let me know where is located.
> [d-date/google-mlkit-swiftpm#16](https://github.com/d-date/google-mlkit-swiftpm/issues/16)

Resolved:
https://github.com/d-date/google-mlkit-swiftpm/issues/16#issuecomment-1274210156

**Comment by alexanderkhitev** [comment]
Hey guys! Any news/updates? Thanks.

**Comment by miworking3** [comment]
Unfortunately this won't be planned in the future release.

**Comment by luca992** [comment]
> Unfortunately this won't be planned in the future release.

So google plan is.... just not planning on supporting devs with a modern arm macbook... sounds like a good plan. What a joke.

**Comment by d-date** [comment]
Really disappointed. Google MLKit might be sunset iOS support.

**Comment by AnatoliBenke-Helsana** [comment]
Any update on that?

**Comment by akirmse** [comment]
I'm unable to move Firebase to SPM because Google's MLKit doesn't support it.  Here's an article that describes how to move to Apple's ML libraries instead to fix the problem:

https://medium.com/@fredadda/ios-strategies-to-transition-to-swift-package-manager-7d954c8abd36

If this doesn't get resolved soon, I will also drop Google's MLKit.

**Comment by Vlastelin1** [comment]
mlkit not work with firebase and admob in spm, app crash

**Comment by ekizsemih** [comment]
any update?

**Comment by pmstani** [comment]
This is really disappointing, it seems like ML Kit won't support iOS going forward.

**Comment by HassanTaleb90** [comment]
Any update? 🤔

**Comment by DongdongGreenDot** [comment]
Hi all
Does MLKit support the Swift Package Manager?

**Comment by DongdongGreenDot** [comment]
Any update? 🤔

**Comment by bartleby** [comment]
+1

**Comment by marvinkome** [comment]
+1

**Comment by drewmccormack** [comment]
Anyone waiting for this probably should stop. Pretty clear this is a policy. Effectively, they are deprecating the SDK on Apple platforms.

**Comment by StefanOltmann** [comment]
Wow, not even offering proper XCFramework files instead is really disappointing.

**Comment by grighakobian** [comment]
+1

**Comment by d-date** [comment]
HI folks,
I'll released unofficial swiftpm support of MLKit for iOS.
Now v5.0.0 has released. Try it out!
https://github.com/d-date/google-mlkit-swiftpm

**Comment by OAK-WJR** [comment]
+1

**Comment by OAK-WJR** [comment]
> HI folks, I'll released unofficial swiftpm support of MLKit for iOS. Now v5.0.0 has released. Try it out! https://github.com/d-date/google-mlkit-swiftpm

Can you please add the google translation into it? I just saw BarcodeScanning and FaceDetection.

**Comment by mtnair** [comment]
Now that Google Maps Platform is deprecating CocoaPods by Q2 2026, any chance MLKit will be migrating to SPM, too?

Got an email from Google last week:

> Hello Google Maps Platform customer,
> 
> To streamline our development and release processes, and align with the evolving iOS ecosystem, we will be phasing out support for **CocoaPods** as an installation method for our **Google Maps Platform iOS SDKs**.
> 
> ### What you need to know
> #### Key changes:
> 
> We will stop releasing new versions of the following Google Maps Platform iOS SDKs through CocoaPods:
> 
> - [Maps SDK for iOS](https://developers.google.com/maps/documentation/ios-sdk/config)
> - [Places SDK for iOS](https://developers.google.com/maps/documentation/places/ios-sdk/config)
> - [Navigation SDK for iOS](https://developers.google.com/maps/documentation/navigation/ios-sdk/xcode-setup)
> - [Fleet Engine](https://developers.google.com/maps/documentation/mobility/fleet-engine)
> 
> CocoaPods [is in maintenance mode](https://blog.cocoapods.org/CocoaPods-Support-Plans/), and **Swift Package Manager** has become the preferred dependency manager for iOS development. Focusing on Swift Package Manager will allow us to dedicate more resources to improving the SDKs.
> 
> We will support releasing new Google Maps Platform iOS SDKs versions (for example: version 10.x.x) through CocoaPods until **Q2 2026**. Starting with version 11.0 of all Google Maps Platform iOS SDKs, new versions will not be released on CocoaPods.
> 
> #### Potential impact:
> 
> If you continue to use CocoaPods after **Q2 2026**, you will not be able to access the latest Google Maps Platform iOS SDKs versions, including new features, performance improvements, and critical bug fixes.
> 
> ### What you need to do
> #### Advised actions:
> 
> We encourage all developers currently using CocoaPods for Google Maps Platform iOS SDKs to begin planning their migration to Swift Package Manager or manual installation to ensure continued access to the latest updates. Learn more about the Swift Package Manager installation instructions in the SDK documentation links above.
> 
> #### Impacted customers/accounts:
> 
> You are using the affected SDKs on the following projects:
> 
> [redacted]
> 
> _You may or may not be using CocoaPods in applications linked to those projects - only applications using CocoaPods are affected._
> 
> ### We’re here to help
> We understand these changes may take some planning. If you have any questions or require assistance, please feel free to contact our support team at [Google Maps Platform Support](https://developers.google.com/maps/support/).
> 
> Thanks for choosing Google Maps Platform.

**Comment by aalzehla** [comment]
any update?

**Comment by joseitor** [comment]
It's really important that this pluging migrate to Swift Package Manager (SPM), why is not happening?

**Comment by bartekgrzymkowski** [comment]
Any update on this issue?

**Comment by fresnohernandez99** [comment]
Im guessing nothing is in works?!

**Comment by mohammedasif580** [comment]
Is there any update for new versions of mlkit in SPM?

**Comment by brosnic** [comment]
Cocoapods is dead! Please support SPM!

**Comment by bevischen2** [comment]
SPM please！！！！

**Comment by sprengerst** [comment]
Maybe you can think about this one again ;) +1

**Comment by konifer44** [comment]
Where SPM ?

**Comment by d-date** [comment]
For anyone still landing here: it is worth reading the release cadence rather than waiting.

ML Kit's iOS releases were roughly every six months — 6.0.0 (2024-04), 7.0.0 (2024-10), 8.0.0 (2025-03), 9.0.0 (2025-06) — and **9.0.0 is still the latest, 15 months on**. The last word from the team in this thread was in 2022, that SPM "won't be planned in the future release". Meanwhile other Google iOS SDKs are moving the other way: Google Maps Platform is deprecating CocoaPods entirely in favour of Swift Package Manager. Draw your own conclusion, but planning around ML Kit iOS being maintained does not look like a good bet.

**For new work, Apple's own frameworks now cover most of what people use ML Kit for**, natively, with no third-party dependency, no resource bundles to copy in, and full Apple Silicon support:

- Text recognition → `VNRecognizeTextRequest` (Vision)
- Barcode scanning → `VNDetectBarcodesRequest` (Vision), or `DataScannerViewController` (VisionKit) for a live camera UI
- Face detection and landmarks → `VNDetectFaceRectanglesRequest` / `VNDetectFaceLandmarksRequest`
- Body pose → `VNDetectHumanBodyPoseRequest`
- Person segmentation → `VNGeneratePersonSegmentationRequest`
- Image classification → `VNClassifyImageRequest`, or your own Core ML model
- Language identification → `NLLanguageRecognizer` (NaturalLanguage)
- On-device translation → the Translation framework (iOS 18+)

**If you do need ML Kit specifically** — translation on older OS versions, Smart Reply, custom TFLite labeling — there is a community SwiftPM wrapper: [d-date/google-mlkit-swiftpm](https://github.com/d-date/google-mlkit-swiftpm). As of [9.0.1](https://github.com/d-date/google-mlkit-swiftpm/releases/tag/9.0.1) the blockers this thread opened with are gone:

- **Apple Silicon Simulator works.** The arm64 simulator slice Google's binaries lack is synthesised from the device slice, so no `EXCLUDED_ARCHS` workaround — that was the original M1 complaint here.
- **App Store submission works.** An upload was accepted by App Store Connect, including the ITMS-91065 signature check that used to reject builds.
- **Every wrapped product runs**, verified by running inference on the Simulator rather than by building: 9.0.1 is the first release where the OCR, pose detection and selfie segmentation models were actually published.

It wraps 17 of the 19 user-facing ML Kit APIs; `DigitalInkRecognition` and `EntityExtraction` are not covered. Two steps stay manual and are documented in the README: `-ObjC -all_load` in *Other Linker Flags*, and adding the resource bundles for the modules you use, since SwiftPM cannot carry them inside a binary target.

**Comment by d-date** [comment]
Small correction to my comment above: [9.0.2](https://github.com/d-date/google-mlkit-swiftpm/releases/tag/9.0.2) adds `DigitalInkRecognition` and `EntityExtraction`, so [d-date/google-mlkit-swiftpm](https://github.com/d-date/google-mlkit-swiftpm) now wraps **every** user-facing ML Kit iOS API — 19 SwiftPM products, nothing left out.

```swift
.package(url: "https://github.com/d-date/google-mlkit-swiftpm", from: "9.0.2")
```

Both new modules download their models from Google on first use rather than shipping them, so they need network access the first time. Everything else is unchanged: Apple Silicon Simulator works without `EXCLUDED_ARCHS`, an App Store Connect upload of a build using all 19 products was accepted, and the two manual steps (`-ObjC -all_load`, plus the resource bundles for your modules) are documented in the README.

The rest of my previous comment stands — if you are starting something new, Apple's Vision, NaturalLanguage and Translation frameworks cover most of this natively and are actively maintained.
