### ISSUE TITLE
Pose detection failed in extracted video frame but success on the live view from that video

### ISSUE THREAD

**Issue by duckyngo** [googlesamples/mlkit#183]
I extracted all frames from the video file to a bitmap and then try to detect the human pose from each video but the MLKit pose detection failed to detect the keypoints. The extracted frame as following: 

On the contrary, when I test by opening the video in big monitor and using the Live Preview function, the MLKit can detect all keypoints successfully as following.

![Screenshot_20201120-105232_MLKit-Vision](https://user-images.githubusercontent.com/22850962/99748056-1caccf80-2b1f-11eb-9d0a-574f832f8bcc.jpg)

I keep the same configuration as the MLKit Live View for pose detection and extract every frames in the time order just like it from the camera. The video size and extracted frame are identical (1066x480) 

At first, I think it was because of the low resolution from the extracted frame compared with camera input and I tried doubling the image resolution but it same not work.
Could you please give me some suggestion to deal with this issue? 
Thank you in advance

**Comment by steven-chengji-yan** [comment]
Hi duckyngo,

With the first image you sent, I can reproduce the issue in Single Image mode: 
![image](https://user-images.githubusercontent.com/3616861/99840498-8201c000-2b21-11eb-907e-94e7239f5113.png)

Then I tried to crop the image horizontally a bit and can get results back: 
![image](https://user-images.githubusercontent.com/3616861/99840592-abbae700-2b21-11eb-9a86-767451565947.png)

The reason is that the person detection model takes in square input frame, so we need to rescale image with whatever aspect ratio to square first. This will result in some distortion of the content for non-square input images, but it is ok for most cases.   For your first image, the aspect ratio looks like more than 2, which will result in very large distortion when rescale.  That is why it fails to recognize the person. 

Could you do some cropping when processing the video, e.g. crop both left and right a little bit, if you mostly care about person in the center?

--------
BTW,
Here is a question about "How to run detector on Video". Personally I haven't done that before. Since you are able to make it work, will appreciate a lot if you could provide some help/code snippet there.  Thanks!

**Comment by duckyngo** [comment]
Thank you a lot for the clear explanation. It works great. Since you try to detect the person in the image first, Is it a good idea to crop the person first before using Object Detection first then feed the cropped image to Pose Detection? 
BTW, I will share my approach to the mentioned question.

**Comment by steven-chengji-yan** [comment]
Hi duckyngo,

You can try applying Object Detection first to make the crop more smart. That will probably help you catch some cases that the person is not around the center of the image. However, do note:
(1) Adding Object Detection will increase your app a bit more because you need to bundle more models to your app.
(2) Running two detectors will slow down the per frame processing more or less
(3) For the ML Kit Object Detection feature, if you don't enable multiple objects, it also only detect prominent centered object in the image.  If you enable multiple object, it will return at most 5 objects, and you will need to crop the image so that the crop area covers all these 5 bounding boxes (should be straightforward logic tho).
