### ISSUE TITLE
object detect not work when change resolution

### ISSUE THREAD

**Issue by rock75923** [googlesamples/mlkit#200]
I use MLKObjectDetector with objective-c, when I set the stream mode(MLKObjectDetectorModeStream) and change image resolution, the detect callback always return the same value, even re-initial and it does't work, if I set image mode(MLKObjectDetectorModeSingleImage) the result will fine, but image mode will NOT return "id", it like some static variable not clear when change resolution

**Comment by bcdj** [comment]
For the streaming mode (MLKObjectDetectorModeStream), when you change the image resolution, have you scaled the detection results to match the dimension of the input video frame?  You can try out the quickstart app for object detection and tracking feature and it does the similar scaling logic here:

https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExampleObjc/CameraViewController.m#L446-L450

For the single image mode (MLKObjectDetectorModeSingleImage), by "id", do you mean the "trackingID"?  If so, it's only returned for the streaming mode (MLKObjectDetectorModeStream), since the object tracking feature (and the returned "trackingID") is only for tracking the same object across a series of video frames in the streaming mode.  For a single image, the object does not move, so  no need to track.

Hope this helps.  Have fun with ML Kit.
