### ISSUE TITLE
MLKit Pose Detection: Retrain MLkit pose detection with current model as pre-training

### ISSUE THREAD

**Issue by duckyngo** [googlesamples/mlkit#202]
Is it possible to retrain the ML Kit pose detection models. The current model work well for general purposes but I am working on just small numbers of particular poses( Maybe 10 poses). So I want to fine-tune the current model with those poses. Could you please tell me how can I improve the current models with specific poses?

**Comment by steven-chengji-yan** [comment]
Hey duckyngo,

If your goal is "more accurate landmarks for the 10 poses you care about", I don't know any straightforward solutions beyond recording it as a feature request. In this case, could you provide more information about what kind of poses are you trying to detect? It would be even better if you could share some of those images with us (but you don't have to if you prefer not).

If your goal is "classifying among the 10 poses", here are some [tips](https://developers.google.com/ml-kit/vision/pose-detection/classifying-poses).

**Comment by duckyngo** [comment]
Thank you for the suggestion. My goal was calculate exactly the angle base on human keypoints. Like this image, I want to calculate angle at ankle but it often fail to detect exact the position of foot index. 

![warrier2_sketch](https://user-images.githubusercontent.com/22850962/102688780-5bc46280-423c-11eb-9673-182a1435f67c.png)

In my application, I detected the necessary postures. There are only about 10 postures so I want to re-train the model to be able to calculate the ankle angle more accurately.

**Comment by steven-chengji-yan** [comment]
hmm... so if I understand correctly, for certain 2 poses that you want differentiate, the only difference is the angle at ankle and all other parts of the body are exactly the same... That would be hard / not reliable for the current model. 
Could you try to instruct the users in some way to achieve larger pose difference that can be more accurately detected?

**Comment by duckyngo** [comment]
Yes, I thought it is hard too. Our purpose is to detect and calculate exactly the angle for analysis, not for classification. The current model is made for the general purpose of pose detection (It can detect many poses). So I really want to custom the model, re-train it with our particular purpose (with just 10 poses which already classified). It would be very good for some particular application.

**Comment by steven-chengji-yan** [comment]
I chatted with some of research folks and hope the following could help you a bit more:

Our training pipeline is not open-sourced at the moment, so yourself using that pipeline with more specific data to re-train the model is out of the scope. However, you can still use your own pipeline to train a model and the ML Kit Pose Detection API could make it significantly easier compared to starting a ML project from scratch.
- Doing it from scratch, you will probably need 1000+ (if not more) annotated images for poses
- Now with the ML Kit API, you already get outputs that are 80% or 90% of the way there. You can feed your specific training dataset of X images through ML Kit Pose SDK and get our outputs then you just need to hand annotate the ankle part to make it more accurate instead of all the landmarks by yourself.
- With all these annotated images from your own dataset, now you can use your pipeline to train a custom model.
- I am sure there are more advanced transfer learning techniques out there too but this is the basic setup IIUC.

With this custom model, you will probably also need to build your own code to run it.

In this case, ML Kit Pose API is mostly like a training data annotation helper.

**Comment by duckyngo** [comment]
Oh, Yes. Thank you very much for your suggestion.

**Comment by Aperico-com** [comment]
Is the re-training policy likely to change for pose detection and be more like it is for for a few of the other APIs?(https://developers.google.com/ml-kit/custom-models)

The reason I ask is that it looks like I will scrap my current project only three days in doing research of the ML kit pose detection. Even with the accurate model it does note even detect a person most of the time, when it detects a person it seems to be accurate about 80%. I am a bit surprised since I am testing it on Yoga poses and this is something you even bring up as an example for application. It feels like the current model is trained on poses when the subject is facing he camera ( I get much better results then but only with accurate model )

**Comment by steven-chengji-yan** [comment]
About "face", you are right, "The user's face must be present in order to detect a pose." as mentioned in https://developers.google.com/ml-kit/vision/pose-detection

We are working on a newer model and going to be launched soon. Please check by then to see if that works better.

For custom model for Pose, we don't have a plan to work on it in 2021Q1. However, we can consider it if we see more related feature request.

As for the current model not detecting poses, would you mind sharing some of images that it fails to detect and we can debug the issue?

Best,

**Comment by duckyngo** [comment]
hey steven, 

Currently, I am having a problem of skip frames in a list of frames in both fast mode and accurate mode.
In a list of images, some images are failed to detect (pose.allPoseLandmarks.size =0) but when we try those images for the second time or third time the pose appears. It means that the pre-processing has a problem or the tracking algorithm not work well.

In the accurate mode, the number of failed detected frames is more than in the fast mode. 

I would like to send you a list of images for debugging it. Please send me your email or tell me how can I send those images to you. 

Hope that the newer model will work better.
