### ISSUE TITLE
Xcode 12.3 Comp. Fix

### ISSUE THREAD

**Issue by MentalGear** [googlesamples/mlkit#210]
Source:
https://github.com/CocoaPods/CocoaPods/issues/10059#issuecomment-695876995

Arm architectures are the default on Xcode 12. To use the vision showcase example app, one has to add x86_64

to these xcode config files
https://github.com/googlesamples/mlkit/blob/64d3cb8d3039de40104978b6a29d8cb317c00b5d/ios/showcase/vision-showcase/ShowcaseApp.xcodeproj/project.pbxproj#L337
https://github.com/googlesamples/mlkit/blob/64d3cb8d3039de40104978b6a29d8cb317c00b5d/ios/showcase/vision-showcase/ShowcaseApp.xcodeproj/project.pbxproj#L390

**Comment by miworking3** [comment]
Thanks for noticing this and deep dive into that @MentalGear MentalGear, it is intended to run the showcase app ONLY on real device,because the user case in this app would require the sample buffer captured from the camera, which is not supported by iOS Simulator. If you want to use the detector for single images, welcome to use our quickstart app from here: https://github.com/googlesamples/mlkit/tree/64d3cb8d3039de40104978b6a29d8cb317c00b5d/ios/quickstarts/vision.

**Comment by MentalGear** [comment]
@miworking3 Yes, I'm aware of this. However the compile issue also appears when trying to deloy directly on device.

**Comment by miworking3** [comment]
- I was able to run it on a real device (iPhone 12 Pro, iOS 14.3) with Xcode 12.3 in `Release` mode without any error. 

- According to the fun facts about Xcode 12 in [this](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios/63955114#63955114) thread, Xcode 12 is looking for `arm64` when building with Simulator as the target, it will cause the problem as current MacOS doesn't support `arm64`, thus getting a compiler error. However when it runs with real device, this is not an issue, as it will use the device instead of the MacOS to build for `arm64`. Given that, since this project is only targeting for real device run, current setting would suffice its needs.

- It is likely that the second time when you built with real device, the residue of the first time of Simulator building was still in the way. Would recommend to start over with a **newly created folder**, `git clone`, `pod install`, select `Release` mode and choose the **device** as target, and start to build to see if the problem will still be spotted. 
-
- And can you also help to confirm the OS version and device type, as well as the Xcode version to reproduce this problem?  Thanks.
