### ISSUE TITLE
MLKVisionImage initWithImage do not release UIImage and app crash

### ISSUE THREAD

**Issue by yoldar** [googlesamples/mlkit#220]
Hi! I'm trying to modify image before giving to MLKit. I'm using CoreImage for it:

```
- (UIImage*)invertImage:(CIImage*)image
{
    @autoreleasepool {
        CIFilter* filter = [CIFilter filterWithName:@"CIColorInvert"];
        [filter setDefaults];
        [filter setValue:image forKey:@"inputImage"];
        CIImage *inverted = [filter valueForKey:kCIOutputImageKey];
        CIContext *context = [CIContext contextWithOptions:nil];
        CGImageRef invertedCGImage = [context createCGImage:inverted fromRect:[inverted extent]];
        UIImage *result = [[UIImage alloc] initWithCGImage:invertedCGImage];
        CGImageRelease(invertedCGImage);
        return result;
    }
}
```

When I start processing memory just grows and app crash:

```
- (void)captureOutput:(AVCaptureOutput *)captureOutput
didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer
     fromConnection:(AVCaptureConnection *)connection {
    
    // CIImage from sampleBuffer
    CVImageBufferRef cvImage = CMSampleBufferGetImageBuffer(sampleBuffer);
    CIImage *ciImage = [[CIImage alloc] initWithCVPixelBuffer:cvImage];
    
    // Invert image
    UIImage *invertedUIImage = [self invertImage:ciImage];
    
    MLKVisionImage *image = [[MLKVisionImage alloc] initWithImage:invertedUIImage];
    AVCaptureDevicePosition cameraPosition = AVCaptureDevicePositionBack;
    image.orientation = [self imageOrientationFromDeviceOrientation:UIDevice.currentDevice.orientation
   cameraPosition:cameraPosition];
    [self.barcodeScanner processImage:image
                      completion:^(NSArray<MLKBarcode *> *_Nullable barcodes,
                                   NSError *_Nullable error) {
      if (error != nil) {
        return;
      }
      if (barcodes.count > 0) {
          for (MLKBarcode *barcode in barcodes) {
             NSLog(@"Barcode value: %@", barcode.rawValue);
               [self cleanupCaptureSession];
               [self->_session stopRunning];
               [self->delegate sendResult:barcode.rawValue];
               break;
           }
      }
    }];
}
```

Strange thing is that XCode couldn't detect any memory leaks problems.

P.s. Using pod 'GoogleMLKit/BarcodeScanning', '~> 0.64.0'

![2021-01-12 16 32 29](https://user-images.githubusercontent.com/1597578/104303273-1a01a180-54f4-11eb-8e28-08643f74a9f5.gif)

**Comment by bcdj** [comment]
`MLKVisionImage`'s `initWithImage:` only holds on its reference to passed in `UIImage` for the duration of its lifetime.  Once the `MLKVisionImage` instance goes out of scope, it will release its reference to the `UIImage`, so ARC should take care of memory management. 

Since your `captureOutput:didOutputSampleBuffer:fromConnection:` video capture delegate callback is invoked in a tight loop, could the growing memory due to the accumulation of intermediate objects?  Did you try wrapping the entire body of the delegate callback inside `@autoreleasepool { ... }`?  Just a thought.  There could be other reasons with the code.

You can try out the quickstart sample app:

https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExampleObjc/CameraViewController.m#L833

It doesn't do image inversion, but does similar things of scanning barcode in the video capture delegate callback.

**Comment by yoldar** [comment]
> `MLKVisionImage`'s `initWithImage:` only holds on its reference to passed in `UIImage` for the duration of its lifetime. Once the `MLKVisionImage` instance goes out of scope, it will release its reference to the `UIImage`, so ARC should take care of memory management.
> 
> Since your `captureOutput:didOutputSampleBuffer:fromConnection:` video capture delegate callback is invoked in a tight loop, could the growing memory due to the accumulation of intermediate objects? Did you try wrapping the entire body of the delegate callback inside `@autoreleasepool { ... }`? Just a thought. There could be other reasons with the code.
> 
> You can try out the quickstart sample app:
> 
> https://github.com/googlesamples/mlkit/blob/master/ios/quickstarts/vision/VisionExampleObjc/CameraViewController.m#L833
> 
> It doesn't do image inversion, but does similar things of scanning barcode in the video capture delegate callback.

Thanks!!!
