### ISSUE TITLE
Text Recognition can not detect vertical aligned characters (For container codes)

### ISSUE THREAD

**Issue by yenthanh132** [googlesamples/mlkit#254]
I am using Text recognition of ML Kit library for detecting Container Codes, there are two options for container codes which are horizontal aligned (normal) and vertical aligned.
Text Recognition can scan all the characters for container codes in horizontal alignment but can not scan characters if the container codes is aligned vertically. Is there any option for tunning the Text recognition or it is because of the limitation of Text Recognition Library? I also tested with online Google Vision API but the result is still the same.

As the below image, it can track the container code in horizontal (KTNU 396009 3) 
![1](https://user-images.githubusercontent.com/4266744/112827624-cd704000-90b8-11eb-96a3-b5811f817453.jpg)
but can't detect the container code in vertical (SRGU 212732 5)
![2](https://user-images.githubusercontent.com/4266744/112827635-d19c5d80-90b8-11eb-86c8-0a0241fca28c.jpg)

**Comment by cs-googler** [comment]
Hi, the model should be able to detect characters. However, since the Characters in your photo is lined with a certain angle, it is hard for the model to detect all of them. When I use the vision quickstart live preview activity, I can get one or two of them recognized.  So, there is space for us to improve the model. Thanks for reporting.

**Comment by yenthanh132** [comment]
Thank you @cs-googler for your comments, It would be great if you can improve the model for this case. I understand that this may take time and the new model won't be improved soon, in the mean time I need to find an alternative solution to detect characters in this special case for my business. Do you have any recommendation for me to address this problem so I can also process by myself first? (I will share the result to improve the model too).

**Comment by fjr619** [comment]
for text recognition can we have custom model? because cant find the documentation for custom model text recognition. and how to create that custom model to improve accuracy?

**Comment by chrisito** [comment]
Sadly this is currently a known limitation of the Text Recognition API that we need to address. Sadly there is no quick fix here, open sourcing the underlying models would not really help.

**Comment by werohit** [comment]
I am facing the same problem.

![device-2021-07-01-152522](https://user-images.githubusercontent.com/65589193/124220570-a859f600-db1b-11eb-82b0-8b7e89e2fc0f.png)

**Comment by yenthanh132** [comment]
I think the best option is to train myself another OCR model for detection this special scenario, close this issue now.

**Comment by sidathgueye** [comment]
> J'utilise la reconnaissance de texte de la bibliothèque ML Kit pour détecter les codes de conteneur, il existe deux options pour les codes de conteneur qui sont alignés horizontalement (normal) et alignés verticalement. La reconnaissance de texte peut scanner tous les caractères pour les codes de conteneurs alignés horizontalement mais ne peut pas scanner les caractères si les codes de conteneurs sont alignés verticalement. Existe-t-il une option pour régler la reconnaissance de texte ou est-ce à cause de la limitation de la bibliothèque de reconnaissance de texte ? J'ai également testé avec l'API Google Vision en ligne mais le résultat est toujours le même.
> 
> Comme l'image ci-dessous, il peut suivre le code du conteneur en horizontal (KTNU 396009 3) ![1](https://user-images.githubusercontent.com/4266744/112827624-cd704000-90b8-11eb-96a3-b5811f817453.jpg) mais ne peut pas détecter le code conteneur en vertical (SRGU 212732 5) ![2](https://user-images.githubusercontent.com/4266744/112827635-d19c5d80-90b8-11eb-86c8-0a0241fca28c.jpg)

Bonjour est ce qu aujourdui vous avew une solution pour ce probleme. je travaille exactement sur le meme projet les nuneros de conteneurs.

**Comment by sidathgueye** [comment]
Bonjour est ce qu aujourdui vous avew une solution pour ce probleme. je travaille exactement sur le meme projet les nuneros de conteneurs.

**Comment by werohit** [comment]
Non, je ne suis pas en mesure de résoudre ce problème avec la bibliothèque. Je travaille donc sur un autre algorithme OCR pour résoudre ce problème. Mais MLKit n'a pas encore fourni de solution pour cela. J'ai vérifié de nombreuses autres bibliothèques OCR et elles ont déjà fourni une solution pour cela.

**Comment by sidathgueye** [comment]
> Non, je ne suis pas en mesure de résoudre ce problème avec la bibliothèque. Je travaille donc sur un autre algorithme OCR pour résoudre ce problème. Mais MLKit n'a pas encore fourni de solution pour cela. J'ai vérifié de nombreuses autres bibliothèques OCR et elles ont déjà fourni une solution pour cela.

Ah super, vous pouvez me partager un lien github sil vous plait? sinon m'indiquer les solutions que vous avez pu utilisé. Merci d'avance

**Comment by RazaShehryar** [comment]
is there any update on this? I am facing a similar issue.

**Comment by RazaShehryar** [comment]
@yenthanh132 did you find a solution for it?

**Comment by akolodkin** [comment]
For anyone still hitting this: a workaround that needs no custom model is to find the stacked characters yourself and re-lay them as a horizontal strip before calling the recognizer.

1. Threshold the paint (a few bright/dark cut-offs), label connected components, keep glyph-sized blobs and cluster them into a column by horizontal centre.
2. Cut each glyph from the full-resolution image and draw them side by side into one strip.
3. Run `TextRecognition` on the strip as a normal line and validate with the ISO 6346 check digit.

On a door photo where ML Kit alone returned only the boxed check digit, the strip pass reads the full number. Detection is ~90 ms on an x86 emulator at 1200 px, plus one small recognizer call.

Two notes: the `rotationDegrees` argument of `InputImage.fromBitmap` did not change what the Latin recognizer read for us, rotating the pixels did; and rotation cannot fix this case anyway since each glyph is already upright.

Android example with tests: https://github.com/cxtms/example-mlkit-vertical-text-fable
