### ISSUE TITLE
Face detection failed com.google.mlkit.common.MlKitException: This detector is already closed!

### ISSUE THREAD

**Issue by DurgaArunkumarSmitiv** [googlesamples/mlkit#259]
I am using MLKit face detection in background service, and on screenoff from power button click , I am closing the camera and stopping frame processor but it is throwing  Face detection failed com.google.mlkit.common.MlKitException: This detector is already closed! , can you please suggest solution to resolve this issue .
![image (7)](https://user-images.githubusercontent.com/47417370/113656026-9dc4c780-96b8-11eb-84c1-ee5c6c6c33c5.png)

**Comment by cs-googler** [comment]
Hi, could you be more explicit about where in the code did you close the detector? 

If nothing goes obviously wrong in your implementation, this is usually caused by a submitted detection task still being executed after the close call is finished. You can check this [ScopedExecutor](https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/ScopedExecutor.java) to see how to eliminate the the possibility of this condition.

**Comment by jackqdyulei** [comment]
Close because of inactivity
