### ISSUE TITLE
Face Detection detects face even with a mask on.

### ISSUE THREAD

**Issue by jishindev** [googlesamples/mlkit#267]
Should the `FaceDetection` model be detecting faces when half of the face is covered? If that's a case you solved for, shouldn't there be a way to disable it for certain use cases which require a full face to be present? 

Also, I see that the Face Landmarks for the nose and mouth were returned with actual values even when they were covered by a face mask. Can anyone throw some light on whats happening here please?

**Comment by bcdj** [comment]
ML Kit's Face API detects partially covered face. When such face is detected, the landmarks are mapped to where they suppose to be regardless such facial features maybe covered. This is by design. Landmarks are a predefined set of points. When a face is detected, the landmarks is mapped to the detected face based on some key factors. This is the reason why landmarks can be returned regardless the face is covered. There is a face detection option to not return any landmarks, but there isn't a way to return only landmarks not covered by the masks.

**Comment by jishindev** [comment]
Thanks @bcdj , understood. 

Do you see any other way by which we can make the Face detector API only detect fully visible faces?
We're trying to use this for a KYC onboarding flow which requires the face to not be partial. 
Would greatly help if you could guide us in the right direction.

**Comment by cs-googler** [comment]
Hi, our current face detection model is quite old and it was optimized for mobile performance so we had to choose some quality performance compromise. It is never intended for the medical application / ml annotation / sizing etc. They are primarily aimed at fun applications.

For your use case, a KYC onboarding flow, I believe you will need biometric facial recognition model which can help you with the identification .

**Comment by jishindev** [comment]
The use case is still very basic even for a KYC onboarding flow @cs-googler, We are only trying to make sure if the face is centred, looking straight and fully visible before we take a picture of the face and proceed further. The first two are taken care of already. It's just the partial faces issue that's left to be solved for, as it is not something that's desired for this particular use-case.

No Biometric or complex functionalities expected out of MLKit here.  

Any plans on updating the models in future though? 

Thanks.

**Comment by bcdj** [comment]
We will definitely continue to improve our models, technologies, and SDKs in the future, but can't share any specific plan at this moment.
