### ISSUE TITLE
Pose detection 

### ISSUE THREAD

**Issue by emadavr** [googlesamples/mlkit#275]
hello
I am a student and work on your pose detection app and I have some problems with your app.
how we can recognize the right movement from the wrong movement in pose detection with the KNN method that you used in your vision-quickstart app?
when we read the CSV file we can not understand the meaning of the numbers in the X, Y, and Z axes? what is the measurement scale of these axes ?

**Comment by steven-chengji-yan** [comment]
Hi emadavr,

Could you provide a concrete example about what do you mean by saying recognizing the right movement from the wrong movement?

The current demo in the app recognizes independent poses, .e.g squat_down, pushup_down...   by saying "movement", are you trying to recognize a sequence of poses?

**Comment by emadavr** [comment]
In this demo app, we only have 2 stages for movement validity. to be more precise, in Squad movement the app has 2 stages which are Squad_up and Squad_down. how we can find out wrong movements if between these stages we have wrong acts, like the wrong distance between knees when the user wants to Squat down or wrong elbows angles?
how we can find out these kinds of movement errors with the KNN method that you use in this demo?
what is your suggestion for tracking whole movements or more stages for increasing the app accuracy?

**Comment by emadavr** [comment]
> Hi emadavr,
> 
> Could you provide a concrete example about what do you mean by saying recognizing the right movement from the wrong movement?
> 
> The current demo in the app recognizes independent poses, .e.g squat_down, pushup_down... by saying "movement", are you trying to recognize a sequence of poses?
> 
> As for the values in .csv file, they are from the pose classifier Colab linked in the [pose classification doc](https://developers.google.com/ml-kit/vision/pose-detection/classifying-poses#pose_classification_and_repetition_counting_with_the_k-nn_algorithm) . Those values are in pixels unit for those sample images we used to generate the csv file. They will be normalized by the [PoseEmbedding](https://github.com/googlesamples/mlkit/blob/7c711537e266b639c289174307db2b672c1e6414/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/posedetector/classification/PoseEmbedding.java#L37) class.

**Comment by steven-chengji-yan** [comment]
If you have targeted unwanted poses in mind, you can add examples of these poses in the sample data and make sure during the exercise, the confidence of those unwanted pose are very low.

If you want to detect arbitrary unwanted poses, you can modify the code [here](https://github.com/googlesamples/mlkit/blob/7c711537e266b639c289174307db2b672c1e6414/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/posedetector/classification/PoseClassifier.java#L165). For example, instead of always taking the top K results, adding a threshold and if none of the topK result are within the distance threshold, just don't return any classification results.  With this change, you can check to make sure squat_down and squat_up have decent scores in the classification results.  If none of them appear, it means the pose is unwanted.

BTW, did you mark this as Closed accidentally or intentionally?
