### ISSUE TITLE
Want to use Pose Detection with GCP Vision AI to use that pretrained model, please guide me How can i use that 

### ISSUE THREAD

**Issue by sattyamjjain** [googlesamples/mlkit#309]

**Comment by steven-chengji-yan** [comment]
Hi sattyamjjain,

I am not very familiar with GCP Vision AI. Could you explain a bit more, including but not limited to:
- Which GCP Vision AI API are you talking about? Any links?
- How do you want to use them together?
- Which exact step(s) you need help with?
- Are you working with Android or iOS?
- ...

Thanks

**Comment by sattyamjjain** [comment]
Hi steven

when I was checking the GCP,  I got Video AI to handle pose detection (https://cloud.google.com/video-intelligence/docs/people-detection)
But the issue is that I want to integrate with real-time streaming, not with the video file
and since  in VIsion AI (https://cloud.google.com/vision) currently, there is no support for Pose detection
I am currently working on android

In short, I want to use the google cloud service to handle the pose detection model to improve the overall performance in my app.

please let me know, what is the best way to handle it

**Comment by steven-chengji-yan** [comment]
Hi sattyamjjain,

Usually, when you run machine learning models on Cloud, you can run a large model, which will give you more accurate results. However, due to the internet roundtrip, it will also take longer, thus hard to achieve real-time.   For ML Kit SDKs, the model inference is purely on device.  To make it work well for real-time, the models are smaller thus usually less accurate than a very heavy model runs on cloud. 

Did you already try ML Kit Pose Detection feature? Do the current models MLKit use fail to meet your accuracy requirements? If that's the case, do you mind sharing some more information about your use cases, e.g. which type of poses?

**Comment by steven-chengji-yan** [comment]
Closing this issue since no reply in more than a week.

**Comment by sattyamjjain** [comment]
Hi, @steven-chengji-yan  Sorry for the late response, I was stuck in something
yes
on-device ML Kit usage is working fine, 
But to implement this thing completely on the device
I think so it will increase the overall size and disturb the performance that's why I want to find a way to improve app flexibility using Cloud

but Thanks I'll check any other solution

**Comment by steven-chengji-yan** [comment]
If the initial download apk size is the concern, you could consider downloading the Pose Detection SDK as a feature module whenever user really need it. See [here](https://developers.google.com/ml-kit/tips/reduce-app-size#advanced_move_optional_ml_features_to_dynamic_feature_modules)

As for performance, if you are talking about latency, I believe on-device is much faster than sending every frame to Cloud and wait for the results. If you are talking about accuracy, some heavy Cloud models can be better than smaller models optimized for on-device.

**Comment by sattyamjjain** [comment]
Ohk Thanks for your support I'll check
