### ISSUE TITLE
Pose Estimation 3D WORLD LANDMARKS

### ISSUE THREAD

**Issue by Alex1899** [googlesamples/mlkit#329]
Hi,

I am looking for a way to use the 3D real world landmarks (measured in meters) in my android app using kotlin. On the media pipe solutions website for pose estimation it shows an example in Python how to access the new 3D world landmarks. However, I could not find how to access these types of landmarks in android (Kotlin).  Any help will be very much appreciated.

**Comment by steven-chengji-yan** [comment]
Hi Alex,

Thanks for your feedback. At the moment, ML Kit doesn't support the Pose World3D. 

Do you mind telling us more information which could help us prioritize this request?
- Did you get a chance to try the MediaPipe version? Does the accuracy meet your requirements?
- What is your use case (if you don't mind sharing)? What is the accuracy requirement for your use case?

Before ML Kit adding the World3D support, could you try the following?:
- The current Pose API already provides you x,y,z values in the same unit - image pixels.
- You could assume certain parts of the body have fixed distance, e.g. distance between two eyes is usually around 0.06 meter. 
- Then in one image, if the 3D distance between two eyes is 6 pixels and the z value of left shoulder is -10 pixels, you could infer the person's left shoulder is about 0.1 meters in front of the center of her/his hips.  You could use other distance as the fixed measure as well, e.g. distance between two shoulders instead of two eyes.

**Comment by Alex1899** [comment]
Hi Steven,

Thanks for your response. 

So I am trying to create a fitness application that analyzes the user's form. To do this, I am measuring angles between different body parts. I was only measuring 2D angles and I realized that I need to take into account the Z coordinate as well if I want to correctly measure the angles for specific user positions, e.g. when the user is standing head towards the camera and I want to measure the minimum angle at the elbow during the bicep curl exercise.  

The acceptable range for accuracy would be above 90%. I was wondering maybe using real-world 3D landmarks would give me more accurate results?  I haven't yet tried using the MediaPipe version but I am going to test it soon. 

Thank you very much for your help. I really appreciate it.

**Comment by steven-chengji-yan** [comment]
Thank you Alex. Please let us know once you try the MediaPipe version. It will be helpful for us to prioritize this in ML Kit. 

Thanks!

**Comment by Alex1899** [comment]
@steven-chengji-yan  Hi Steven, 

I have tried using the mediapipe version, however, it did not meet the accuracy requirements. I used the 3D world landmarks to measure angles between body vectors, i.e. upper arm vector and forearm vector (created using 3D landmark coordinates) to get the elbow angle.  However, measured angles are inaccurate. For example, when a person is standing at a 45-degree angle to the camera and flexes the elbow, the minimum elbow angle shown is 120+ degrees, when it's clearly a lot less than this number. It should be less than 60 degrees. The angle calculated using only X, Y coordinates shows less than 60 degrees.  

I would prefer to use a real-world 3D angle if possible and not be restricted by the screen 2D. I want to create an app that exists in 3D space and can reveal the details of good technique, without being limited to a particular position of the user.

If you have any recommendations on how to utilize the Z coordinate to get accurate angle measurements or just any advice on how to proceed it would be greatly appreciated :)

**Comment by steven-chengji-yan** [comment]
Thanks for trying the MediaPipe version and sharing the findings.

I think the challenging part is that for both the MediaPipe World3D and the MLKit experimental Z value, the accuracy of the Z dimension is somewhat less accurate compared to x and y. And this is because the input image is a 2D image without any depth information, so the model/algorithm is guessing the Z value instead of calculating it.

Let me share this feedback to our research team to see how they could further improve it.

Thanks.

**Comment by steven-chengji-yan** [comment]
Hi Alex,

The MediaPipe team got back to me that the current World3D is the first version they release. It is in development and they will work on improvements based on use cases feedback.  ML Kit will consider integrating with it when it is more production-ready.

Thanks!

**Comment by eleiannu** [comment]
@steven-chengji-yan Hi, are there news regarding the integration of World3d in ML Kit?

**Comment by steven-chengji-yan** [comment]
Previously, when we evaluate it internally, we decided to not include it in ML Kit. 

Could you tell us a bit more about your use cases? 
- Streaming mode v.s. Single image? 
- What is the common poses for your case (e.g. fitness, dance, halfbody v.s. full body?, sideway v.s. frontal?, or what else)? 
- Why the existing Z value won't fit your use case?
- How accurate is required to make your case work?  (As Alex mentioned earlier, the MediaPipe World3D didn't meet his accuracy requirement.)

These would be helpful when we do another round of evaluation later to see if the World3D can really achieve what you are looking for.

**Comment by eleiannu** [comment]
@steven-chengji-yan Thank you for your quick reply! It would be Streaming mode, I would need to compute angles and distances in people doing physical exercises in full body and most of the times (but not always) sideways. I tried computing angles using the existing Z value and it was strangely less precise than with the 3d Z. In particular the MediaPipe World3D was accurate enough when it came to computing angles in my case.

**Comment by steven-chengji-yan** [comment]
I see. Thanks for your feedback Elena. We will re-evaluate it at a later time.

**Comment by edi2212** [comment]
GAhQ02Nf8UhrI0rKOQyFuyiHshT8bSK9kSModIXD0X9oycv7etqLhe6+rTZZZcXqFfPx4XgtQiU
