### ISSUE TITLE
ML kit - Text Recognition : Wrong extracted characters on national ID (NID)

### ISSUE THREAD

**Issue by Amr-Elmadah** [googlesamples/mlkit#339]
When I try to detect text on the NID and the text should be "IO7879979" but the extracted text is "107879979" and I know the problem is in the used font on the NID card as I tried the same text on a doc file and it works fine but what should we do on that case as the users will just use their NIDs?

**Comment by chrisito** [comment]
Since the Text Recognition API does not know the right formatting of the NID number, it assumed the whole string of characters was a number. We want to support custom dictionaries in the future with which you will be able to specify restrictions to what is detected (e.g. indicating that you are looking for [A-Z][A-Z][0-9]+. Sadly, we don't support this right now. I think you may need to apply some heuristics in your app to map 1 --> I and 0 to O (and so forth) for the first two detected digits.

**Comment by Amr-Elmadah** [comment]
Thanks for your reply, yes that's what we had decided to do actually in our case 🤗
