### ISSUE TITLE
Android mlkit:pose-detection

### ISSUE THREAD

**Issue by liuyunlong-pro** [googlesamples/mlkit#344]
pose-detection:17.0.1-beta4 app crashed
 A/art: art/runtime/indirect_reference_table.cc:132] JNI ERROR (app bug): local reference table overflow (max=512)
 A/art: art/runtime/indirect_reference_table.cc:132] local reference table dump:
 A/art: art/runtime/indirect_reference_table.cc:132]   Last 10 entries (of 512):
 A/art: art/runtime/indirect_reference_table.cc:132]       511: 0x13092fe8 java.util.ArrayList
 A/art: art/runtime/indirect_reference_table.cc:132]       510: 0x7056cae0 java.lang.Class<java.util.ArrayList>
 A/art: art/runtime/indirect_reference_table.cc:132]       509: 0x7056cae0 java.lang.Class<java.util.ArrayList>
 A/art: art/runtime/indirect_reference_table.cc:132]       508: 0x7056cae0 java.lang.Class<java.util.ArrayList>
 A/art: art/runtime/indirect_reference_table.cc:132]       507: 0x7056cae0 java.lang.Class<java.util.ArrayList>
 A/art: art/runtime/indirect_reference_table.cc:132]       506: 0x7056cae0 java.lang.Class<java.util.ArrayList>
 A/art: art/runtime/indirect_reference_table.cc:132]       505: 0x7056cae0 java.lang.Class<java.util.ArrayList>
 A/art: art/runtime/indirect_reference_table.cc:132]       504: 0x7056cae0 java.lang.Class<java.util.ArrayList>
 A/art: art/runtime/indirect_reference_table.cc:132]       503: 0x7056cae0 java.lang.Class<java.util.ArrayList>
 A/art: art/runtime/indirect_reference_table.cc:132]       502: 0x7056cae0 java.lang.Class<java.util.ArrayList>
 A/art: art/runtime/indirect_reference_table.cc:132]   Summary:
 A/art: art/runtime/indirect_reference_table.cc:132]       511 of java.lang.Class (2 unique instances)
 A/art: art/runtime/indirect_reference_table.cc:132]         1 of java.util.ArrayList
 A/art: art/runtime/indirect_reference_table.cc:132]

**Comment by steven-chengji-yan** [comment]
Hi liuyunlong-pro,

Thanks for actively providing feedbacks to our SDK, but just a general ask: could you help include more details when asking a question in the future?

For this specific issue:

- I tried the vision-quickstart app (proguard build) with pose-detection:17.0.1-beta4 on a Pixel3XL with API30. It works fine.
- What is your setup/steps that can reproduce this issue? 
- Does the vision-quickstart app work for you? Which devices / OS levels did you test? Did they all fail with the same crash?
- Which build type are you using?
- Our latest pose SDK is 17.0.1-beta5. Could you try if that works for you?

Best,

**Comment by liuyunlong-pro** [comment]
HI,
1.phone:vivo x9 with API 25 
2.17.0.1-beta5 also has problems
3.No problem with version 17.0.1-beta3

**Comment by liuyunlong-pro** [comment]
HI,
1.phone:vivo x9 with API 25
2.17.0.1-beta5 also has problems
3.No problem with version 17.0.1-beta3

**Comment by steven-chengji-yan** [comment]
Hi liuyunlong,

We tested this feature on API 25 on our devices but didn't observe the issue you mentioned. Since we don't have a vivo x9, could you help provide a bit more clarification as mentioned earlier? Specifically:

- What is the exact steps to reproduce the issue with the mlkit vision-quickstart app? Does it happen to all StillImageActivity, LivePreviewActivity and CameraXLivePreviewActivity? Does it crash immediately after you select Pose Detection?
- Did you try it on other devices or vivo x9 with higher API levels? Does they all fail with the same issue?

Thanks!

**Comment by liuyunlong-pro** [comment]
mlkit vision-quickstart app will not have this problem.
I wrote it according to the documentation,It is written differently from mlkit vision-quickstart app.


![image](https://user-images.githubusercontent.com/24238955/131318768-5b2d6e04-d13f-433b-866b-b9f968503d67.png)

**Comment by steven-chengji-yan** [comment]
Hi liuyunlong-pro,

In this github repo, we typically focus on common SDK issues and don't debug for specific apps.

Since the vision-quickstart app works, could you try comparing the difference between your implementation and the quickstart?

- When you say quickstart works, did you check the CameraXLivePreviewActivity?
- When you creating your cameraX analysis use case, do you set it up in [the same way](https://github.com/googlesamples/mlkit/blob/3eb63ccc5a42315e87a9e40fd9371d1c2c837cc5/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/CameraXLivePreviewActivity.java#L442) as the quickstart? 
- Which version of CameraX are you using? Maybe you can try switching to the version the quickstart is using and see if the issue is still there. Please search for "camerax" in the [build.gradle](https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/build.gradle) file and check the version.
- ML Kit provides a CameraX helper library as well, which may help you avoid some common issues. Please check [this](https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/CameraXSourceDemoActivity.java).   To use it, you need to add the following to your gradle file: implementation 'com.google.mlkit:camera:16.0.0-beta1'

**Comment by liuyunlong-pro** [comment]
It's different from  quickstart, It's too complicated
There's still a problem with  'com.google.mlkit:camera:16.0.0-beta1'
this problem does not occur in 17.0.1-beta 3

**Comment by steven-chengji-yan** [comment]
Close due to no response.

**Comment by wangzi815** [comment]
> We reproduced the issue on a Pixel device with API level 25 and made a fix. The fix will be out in our next release (early December as planned).
> 
> We also noticed that, on the same Pixel device, if we flashed it to API level 29, the issue is gone. If you have time, please try flashing your device with issue to API 29+ and see if you still observe the issue. This could give us more confidence that the issue we fixed is the same one as you observed.

i test on phone:HRY-AL00,the API level is 29+,but the problem produce again. google/mediapipe#2604 is just mentioned by me.

**Comment by steven-chengji-yan** [comment]
Re wangzi815:

I see. Based on the stacktrace, the size of the ref table is 512, which is relatively small and could cause the issue. Our fix is to release some java class reference more eagerly by ourselves instead of relying on the system to release them. ML Kit will release the new version in December, please give it a try.   For MediaPipe, I just asked their team to provide a release timeline for google/mediapipe#2604

**Comment by steven-chengji-yan** [comment]
FYI: fix is released in ML Kit Dec release. Pose SDK version: 17.0.1-beta7
