### ISSUE TITLE
iOS | PoseDetection - Sudden FPS drop on iPad 8th gen. (a12 chipset)

### ISSUE THREAD

**Issue by MohsinTariqKhan** [googlesamples/mlkit#356]
When using PoseDetection on iPad 8th gen. (a12 chipset) the frame-rate drops significantly around 45 seconds after starting the pose detection. This happens only once when starting pose detection from an idle state.

This issue can be observed in the screen recording video linked below.

https://drive.google.com/file/d/186czWlzrypaUWGVRKCFQwzY_bfLVi33q/view?usp=sharing

**Comment by bcdj** [comment]
Do you have a link to the original video you used for the testing?  Can you reproduce the same issue using the pose detection in the video streaming mode of ML Kit's [quickstart vision sample app](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision)? I tried that on a few videos and didn't notice the slow down on an iPad 8th gen.

**Comment by MohsinTariqKhan** [comment]
> Do you have a link to the original video you used for the testing? Can you reproduce the same issue using the pose detection in the video streaming mode of ML Kit's [quickstart vision sample app](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision)? I tried that on a few videos and didn't notice the slow down on an iPad 8th gen.

Yes I am using this gif for testing.
https://ar.pinterest.com/pin/805651820821121256/

Yes, I am using the same vision sample app without any modifications and you can observe in the video (which i shared previously) that I am already using the video streaming mode to produce this issue.

To reproduce it please follow these steps:-
- Clean install the sample app on iPad 8th gen. (a12 chipset) when your device is in rested state (not heated up)
- Select the video streaming mode from the segment control at the top
- Switch to back camera
- Select PoseDetection from the list of Detectors
- Aim the camera towards the testing gif (link above)
- Let it run for at least a minute or more -> you will notice the issue occur at around 40 seconds or more into the testing.

It only occurs once when you follow the above steps then after further testing it does not re-occur.

**Comment by bcdj** [comment]
Thank you for the test image and the detailed steps.  Yes, I'm able to reproduce the same issue on an iPad (8th generation) running iOS 14.0.1.  The slowdown happened between 1' (minute) and 1'10" (for ~10 seconds) after the pose detection had started.  I will ask the team to investigate and post here when we have an update.

**Comment by bcdj** [comment]
We suspect this is due to CPU throttling. For simplicity, ML Kit's quickstart sample app renders the image using CPU and pose detection is also done on CPU.  In your app, you may want to look into rendering your camera image on a background thread and then applying onscreen on the main thread. In addition, you should consider using the GPU to render the image onto the screen. Furthermore, it's better to use GPU to pre-render all the detection visualization elements into the image on a background thread before using GPU to render the image to screen. An intermediate solution would be to use CoreGrpahics to render the elements into the image on a background thread before using GPU to render the image to the screen buffer (e.g. MTKView, GLKView, etc.). This could reduce the contention with pose detection for the CPU and alleviate potential CPU throttling.
