### ISSUE TITLE
Multiple detections at once?

### ISSUE THREAD

**Issue by utsavDave97** [googlesamples/mlkit#376]
Hello,

Could you guys please give an example where BarcodeScanner and TextRecognizer can be used at the same time for below statement in MLKit.

_GMV provides MultiDetector, MultiProcessor and FocusingProcessor frameworks for performing multiple detections and results filtering. ML Kit does not provide such mechanisms, but the same functionality can be implemented by the developer if desired._

**Comment by zhouyiself** [comment]
Sorry for the late reply.

You can use [Tasks.whenAllComplete](https://developers.google.com/android/reference/com/google/android/gms/tasks/Tasks#public-static-taskvoid-whenall-task...-tasks) API to chain #process from multiple detectors. Here's a sample for how to chain barcode scanner and text recognizer:

```
      BarcodeScanner scanner = BarcodeScanning.getClient();
      TextRecognizer recognizer = TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);
      Tasks.whenAllComplete(scanner.process(inputImage), recognizer.process(inputImage))
          .addOnSuccessListener(
              tasks -> {
                for (Task<?> task : tasks) {
                  Object taskResult = task.getResult();
                  if (taskResult instanceof Text) {
                    Text text = (Text) taskResult;
                    // Handle text result.

                  } else if (taskResult instanceof List<?>) {
                    List<?> resultList = (List<?>) taskResult;
                    if (!resultList.isEmpty() && resultList.get(0) instanceof Barcode) {
                      List<Barcode> barcodeList = (List<Barcode>) resultList;
                      // Handle barcode list result.
                    }
                  }
                }
              });
```

Although the check is bit tricky here if the detector is returning a list because **instanceof** can only be used to check a list with generic type.

**Comment by utsavDave97** [comment]
Appreciate your response @zhouyiself . I got the idea from your code and will close this now.

**Comment by edi2212** [comment]
пн, 15 нояб. 2021 г., 14:55 Utsav Dave ***@***.***>:
