### ISSUE TITLE
Can Digital Ink Recognition work with PencilKit on iPadOS?

### ISSUE THREAD

**Issue by RogVok** [googlesamples/mlkit#391]
It's more of a question/suggestion/request.
Are there any intentions to befriend Google MLKit Digital Ink Recognition with PencilKit?

In the current version, you use a large `UIImageView` as a canvas and interpret `User Interactions` as strokes. This approach is OK but can be better. Issues that I encounter:
- When writing with my Apple Pencil I create lots of false strokes with my hand or fingers. 
- Working with strokes is more difficult in Google MLKit (saving, recreating, converting them to image, etc.)
- The lack of PencilKit ink-specific stuff like pressure, color palette. And Pencils toolkit, eraser.

Is it currently possible to send data from PencilKit (like stroke paths) to the Digital Ink Recognition engine?
Do you plan to utilize PencilKit in the future?

**Comment by miworking3** [comment]
Hi Rog, 

Thanks for the feedback, these are valid points. We discussed this internally, and I'm afraid currently we don't have a plan to support the PencilKit in the near future.  Some detailed comments on the requests as below:

- `When writing with my Apple Pencil I create lots of false strokes with my hand or fingers.`
Our research team acknowledged that this is a valid use case, and can be handled at an application level to allow the strokes to be cancelled when the stylus gets close to the screen.  Currently our quickstart app doesn't handle this as we were trying to keep it simple for core SDK usages. 

- `Working with strokes is more difficult in Google MLKit (saving, recreating, converting them to image, etc.)`
We acknowledges that this requires some conversion utilities. Thanks for bringing this up, we will keep a close eye on this in our customer feedbacks and allocate resource on this when we see more requests on this.

- `The lack of PencilKit ink-specific stuff like pressure, color palette. And Pencils toolkit, eraser. `
This will require to train models for digital ink recognition, I'm afraid this is not feasible currently due to some concerns.
