### ISSUE TITLE
使用cameraX进行pose时图像分析层的图像是左右翻转的，使用bitmap水平镜像又会影响速度，请问有什么好的方法吗？谢谢

### ISSUE THREAD

**Issue by 572120986** [googlesamples/mlkit#396]

**Comment by steven-chengji-yan** [comment]
Hi, 
I am not sure I fully get your question. Could you provide more details? 
1. What's your setup? How do you connect CameraX with ML Kit?
2. What is your expected output?
3. What is the actual output?

**Comment by steven-chengji-yan** [comment]
I will close this issue due to inactivity. Feel free to re-open if you still want to followup.

**Comment by 572120986** [comment]
Hello, the problem is that when MLKIT uses the front camera of CameraX for pose estimation, the landmarks of key points identified are mirrored left and right with the coordinates of the key points corresponding to the original imageProxy of each frame. The previous solution is to transform the image of each frame to bitmap for Matrix image inversion. However, it will affect the recognition speed of each frame, but this problem has been solved. thank you

**Comment by steven-chengji-yan** [comment]
Instead of flipping the image via Bitmap which is slow, could you flip the pose landmark coordinates which is what we do in the vision-quickstart app: https://github.com/googlesamples/mlkit/blob/2f80c301bae79136efa9096881b6e44bee7866a3/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/CameraXLivePreviewActivity.java#L456-L464
