### ISSUE TITLE
Can you add a callback API to identify the completion of ink recognition after success

### ISSUE THREAD

**Issue by AiFocus** [googlesamples/mlkit#452]
Can you add a callback API to identify the completion of ink recognition after success?

**Comment by steven-chengji-yan** [comment]
If you are talking about Android(would be helpful if you could mention it in the question next time based on our template), there is already a [recognize](https://developers.google.com/android/reference/com/google/mlkit/vision/digitalink/DigitalInkRecognizer#recognize(com.google.mlkit.vision.digitalink.Ink)) API that returns a Task. And you can [add listener](https://developers.google.com/android/reference/com/google/android/gms/tasks/Task) to the Task.

**Comment by steven-chengji-yan** [comment]
Saw your other question https://github.com/googlesamples/mlkit/issues/453. I think you should be using Android.

**Comment by AiFocus** [comment]
> If you are talking about Android(would be helpful if you could mention it in the question next time based on our template), there is already a [recognize](https://developers.google.com/android/reference/com/google/mlkit/vision/digitalink/DigitalInkRecognizer#recognize(com.google.mlkit.vision.digitalink.Ink)) API that returns a Task. And you can [add listener](https://developers.google.com/android/reference/com/google/android/gms/tasks/Task) to the Task.

Yes, I used it on Android and encountered this problem, so I give you feedback. According to your reply, the subsequent version will add the callback API after the success of ink recognition for developers to use, is that what I understand？

**Comment by AiFocus** [comment]
> > If you are talking about Android(would be helpful if you could mention it in the question next time based on our template), there is already a [recognize](https://developers.google.com/android/reference/com/google/mlkit/vision/digitalink/DigitalInkRecognizer#recognize(com.google.mlkit.vision.digitalink.Ink)) API that returns a Task. And you can [add listener](https://developers.google.com/android/reference/com/google/android/gms/tasks/Task) to the Task.
> 
> Yes, I used it on Android and encountered this problem, so I give you feedback. According to your reply, the subsequent version will add the callback API after the success of ink recognition for developers to use, is that what I understand？



> Saw your other question #453. I think you should be using Android.

I have seen that in Task there is a callback method after recognition success, but it will callback many times, actually I only need to get the last recognition result, the most correct recognition result.

**Comment by steven-chengji-yan** [comment]
Could you provide more details to help us understand your question more clearly?

- Are you using the ML Kit digital ink sample app?
- What are your action steps to reproduce the issue in the sample app? e.g. click A, then click B, then...
- Which exact callbacks are invoked multiple times after what actions (e.g. is that you click a certain button only once but the callback is called X times? How many times?)? If you can point to the exact line of the code, it will be great.

**Comment by AiFocus** [comment]
Yes, I am using the ML Kit digital Ink sample application, as marked in the screenshot below.
![b050bdb41a8ec1e387933ffb6698093](https://user-images.githubusercontent.com/22763683/156729720-fd1782f3-a7d0-4d8d-ac13-9bc7a21141ef.png)

**Comment by steven-chengji-yan** [comment]
I tried the digital ink app without any changes on Pixel3XL real device with API level 31, and cannot reproduce the issue.

I only got recognition log once after I click the RECOGNIZE button.

In the app, we have a method called [setTriggerRecognitionAfterInput](https://github.com/googlesamples/mlkit/blob/4be2fe856e0b3fd95af370fe5413a33494698067/android/digitalink/app/src/main/java/com/google/mlkit/samples/vision/digitalink/DigitalInkMainActivity.java#L52). It is set to false by default.  However, by looking at your log, it looks like triggering one direction whenever you input something - basically the expected behavior for when this flag is set to true.   Could you check if you accidentally change that flag somewhere?

If that is not the case, I would suggest you to follow the code call chain to understand why this run() method here is called multiple times - which callback at the first place triggers this chain of logic.

**Comment by steven-chengji-yan** [comment]
Close due to no response. Feel free to re-open if you are still working on this.
