### ISSUE TITLE
Whats the best format for InputImage

### ISSUE THREAD

**Issue by manwithsteelnerves** [googlesamples/mlkit#484]
Currently I have image plane buffers as byte arrays and would like to know whats the best format to use for InputImage.
Can someone explain to what internal format InputImage data gets converted to?

Right now it takes Image, Bitmap and ByteBuffer. Would like to know whats the format it finally uses internally so that I can pass the data accordingly to avoid further conversions.

Also, any way to create Image.Plane object instance?

**Comment by zhouyiself** [comment]
It depends on features. Which SDK are you using?

**Comment by manwithsteelnerves** [comment]
Barcode, Pose and Object detection

**Comment by manwithsteelnerves** [comment]
> ML Kit already optimizes the image conversion (if needed) internally. My general suggestion for you would be just passing in whatever image format you can get directly without extra preparation on your layer. In such case, only required conversion will be done once and only when it is needed.
> 
> If you are still curious about the current performance for each format, you could set up your app and measure the latency for each case. Based on my testing with the ML Kit vision quickstart app in streaming mode, for Barcode and Object Detection, Image format (CameraX) is slightly slower than ByteBuffer format (Camera1). For Pose, Image and ByteBuffer perform similarly. As for Bitmap, it is for single image use case and probably we shouldn't compare it with the streaming use case at the first place.
> 
> If you do your own measurement, you should measure the entire end-to-end latency, including the time you spend to get the image with specific format, because that is the latency your app users will experience.
> 
> Close it for now. Feel free to follow up.

Thats quite surprising to see ByteBuffer (NV21) performing well. I explored a bit and found out it internally storing in IImage (planes) format and thought Image will do better.

Also, Is it possible to construct an Image format from other formats? 
I have planes data constructed as AImage (in NDK). To pass it to Java, is it possible to construct Image instance on Java?

**Comment by steven-chengji-yan** [comment]
I did some Google search for "[How to construct android.media.Image](https://www.google.com/search?q=How+to+construct+android.media.Image&sxsrf=ALiCzsZNevTdjmKni2tuo2vX8_Gy4ajQOg%3A1654620496490&ei=UIGfYoazHZmtqtsPv6q32A4&ved=0ahUKEwiGm7nX5Zv4AhWZlmoFHT_VDesQ4dUDCA4&uact=5&oq=How+to+construct+android.media.Image&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECc6BwgAEEcQsANKBAhBGABKBAhGGABQ6QFY6QFg7AZoAnABeACAAZgBiAGYAZIBAzAuMZgBAKABAcgBCMABAQ&sclient=gws-wiz)". Saw some related posts, but didn't find one with broad agreement. Since it is not specific to ML Kit, I would suggest you to do some search and give them a try. If not working, you could consider asking in a more general forum like StackOverflow.

BTW,  based on my experience so far, I would just use Bitmap or ByteBuffer, if I am not given media.Image directly.
