### ISSUE TITLE
How to convert MLImage to UIImage to get  Data in Swift 

### ISSUE THREAD

**Issue by vnanaware** [googlesamples/mlkit#489]
How to get image data on MLImage in iOS pose detection?

     Tried below code but not woring.
    Please suggest how to convert.

    guard let inputImage = MLImage(sampleBuffer: sampleBuffer) else {
          print("Failed to create MLImage from sample buffer.")
          return
        }
      
    inputImage.orientation = orientation
      let img=inputImage.image?.jpegData(compressionQuality: 0.75)

**Comment by vnanaware** [comment]
??

**Comment by bcdj** [comment]
You can get what you passed in, i.e. if you create the `inputImage` with an `sampleBuffer`, you can retrieve the original sample buffer from `inputImage.sampleBuffer?`, but `inputImage.image?` will be `nil` since you didn't create the `inputImage` with an `UIImage`.  Similarly, if you had created the `inputImage` with an `UIImage`, then you would be able to retried the original `UIImage` from `inputImage.image?`, and `inputImage.sampleBuffer?` would be `nil`.

**Comment by vnanaware** [comment]
Ok thanks
