### ISSUE TITLE
recorded video selfie segmentation

### ISSUE THREAD

**Issue by gururajKp** [googlesamples/mlkit#512]
Hi I got selfie segmentation for gallery video in android and it is working perfectly. I didn't get selfie segmentation for photo library saved videos in iOS could some one help me to get the code for IOS. Or send any reference link. It is working good for images selected, live camera in iOS.

**Comment by bcdj** [comment]
Basically you need to get the individual CMSampleBuffer from your gallery video, then feed the CMSampleBuffer to the selfie segmentation API.  You can do some Google searches to hopefully find some sample code for retrieving the CMSampleBuffer from a video file, likely using the AVFoundation's AVPlayer, AVPlayerItem, AVPlayerItemVideoOutput, copyPixelBuffer, etc, to get the CVPixelBuffer and then convert it into a CMSampleBuffer (possibly using CMSampleBufferCreateForImageBuffer). 

Closing this issue since it's not specific to ML Kit SDK.

**Comment by Harshad0011** [comment]
hi @gururajKp i wanted to know if you have any idea how can I process pre recorded video through mlkit's pose estimation model
