### ISSUE TITLE
Get the final output

### ISSUE THREAD

**Issue by gururajKp** [googlesamples/mlkit#515]
How to get final segmented video from this app ?

**Comment by bcdj** [comment]
On you on Android or iOS? Please provide a bit more info using the following template so that we can better help you:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Example Steps to reproduce the behavior in sample app:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

If applicable, please include `code snippet` and `sample input(image, video, text, etc)` 

**Expected behavior**
A clear and concise description of what you expected to happen.

**SDK Info:**
 - SDK Name & Version [e.g. com.google.mlkit:face-detection:16.1.3]

**Smartphone:**
 - Device/Simulator: [e.g. iPhone6, Pixel 5]
 - Device/Simulator OS: [e.g. iOS8.1, Android API 30]

**Development Environment:**
*(For Android issue feel free to skip this section)*
- IDE Eversion: [e.g. Xcode 13.1, Android Studio 4.2]
- Laptop/Desktop: [e.g. iMac Pro (2017), HP Z840 Workstation]
- Laptop/Desktop OS/version: [e.g. macOS 12.0.1]

**Comment by gururajKp** [comment]
I am on Android

Describe the bug
As I am getting the Video on SimpleExoPlayer I want to save that output with segmentation. So how can I save that Segmented video ? 


Expected behavior
I want to save segmented video for further use.

SDK Info:

'com.google.mlkit:face-detection:16.1.2'
Smartphone:

Device/Android API 30 and below
Development Environment:
(For Android issue feel free to skip this section)

IDE Eversion: Android Studio 4.2
Desktop: Windows 10

**Comment by steven-chengji-yan** [comment]
As shown in the ML Kit vision quickstart app, you can combine the camera input and the segmentation mask to generate a single frame with segmentation.  As for how do you combine all the frames and save it to a video file, it is out of the scope of ML Kit SDK. I would suggest to research it via Google search or in places like StackOverflow.
