### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by sudharsanpremkumar** [googlesamples/mlkit#517]
Language download happens multiple times in the same viewcontroller. My project requirement is once download is complete it should navigate to new page.

**Comment by bcdj** [comment]
Which ML Kit feature are you using? Please fill in the following info so that we can better help you:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Example Steps to reproduce the behavior in sample app:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

If applicable, please include `code snippet` and `sample input(image, video, text, etc)` 

**Expected behavior**
A clear and concise description of what you expected to happen.

**SDK Info:**
 - SDK Name & Version [e.g. com.google.mlkit:face-detection:16.1.3]

**Smartphone:**
 - Device/Simulator: [e.g. iPhone6, Pixel 5]
 - Device/Simulator OS: [e.g. iOS8.1, Android API 30]

**Development Environment:**
*(For Android issue feel free to skip this section)*
- IDE Eversion: [e.g. Xcode 13.1, Android Studio 4.2]
- Laptop/Desktop: [e.g. iMac Pro (2017), HP Z840 Workstation]
- Laptop/Desktop OS/version: [e.g. macOS 12.0.1]

**Comment by bcdj** [comment]
Closed due to inactivity.
