### ISSUE TITLE
Detect Person's clothing color 

### ISSUE THREAD

**Issue by Usama99786** [googlesamples/mlkit#547]
I am creating an android app and I want to detect a person's clothing color. i.e. detect the color of the person's shirt. I did some Research on Object detection. I checked the 'DetectedObject' object and it provides getBoundingBox(), getTrackingId(), and getLabels(). How can I find the color of the detected object?

**Comment by ai-plays** [comment]
Hi Usama99786,

ML Kit doesn't provide a cloth color detection solution at the moment and no plan to add it soon.

Some ML Kit features that might be helpful for you to build such a solution are Pose detection and Selfie segmentation. For example, if you want to check the color of the shirt, the pose detection landmarks could help you roughly understand where is the area of the person's upper body, then you can take some sample pixels of that area to understand the color.  Optionally, you could use selfie-segmentation with Pose detection to help you know exact area of the person, rather than just some body landmarks.

Google's MediaPipe offers a solution by combining the Pose detection and segmentation into one [here](https://google.github.io/mediapipe/solutions/pose.html#segmentation_mask). You may need a bit extra time to learn how to set it up though.

Just some suggestion based on my understanding about related technology. However, I would assume, depending on your requirement and use cases, it will still take some effort to get a very high quality solution for your goal. Feel free to come back and share if you build something working so that it inspires others as well :)
