### ISSUE TITLE
object-detection can't detect basketball in human hand?

### ISSUE THREAD

**Issue by liuyunlong-pro** [googlesamples/mlkit#556]
Holding a basketball in hand, the screen can detect the basketball when it is close, but it cannot be detected when it is 1 meter away

**Comment by ai-plays** [comment]
Hi,

This is expected behavior based on current implementation.

For object-detection, by default, it detects [the most prominent](https://developers.google.com/ml-kit/vision/object-detection#key_capabilities) (occupy decent space in the frame, around the center of the frame) object in the frame. 

When the basketball is 1 meter away, it could be too small within the frame.

The following may address your case:
- You could try enabling **multiple object** detection via the Options class, to see if it helps you to catch the small object.
- I did some test: in Streaming mode, if you put your camera close to the object first, confirm a detection, then move backwards, the object should be able to be tracked in couple meters (may vary depending on how large the object is and if there are other objects around it).

Feel free to follow up if you have related questions to this topic.
