### ISSUE TITLE
mask of object detection

### ISSUE THREAD

**Issue by rtz333** [googlesamples/mlkit#557]
Is there any way to get the mask of the object like selfie segmentation mode instead of just getting the surrounding rectangle like now?

**Comment by ai-plays** [comment]
This is not supported by ML Kit Object Detection & tracking API.

Depending on your use case, maybe you could try combining the object detection API with segmentation API (detect the object area first and run segmentation on the sub area) or you need to do some your own research on "Object segmentation" via Google Search.

The former idea could be a little bit hacky because the ML Kit selfie segmentation API was trained with Selfie images, but it may work for your cases as based on our testing it could do some segmentation on objects as well.
