### ISSUE TITLE
startIfReady() is called in onLayout()

### ISSUE THREAD

**Issue by haihuynhrdf** [googlesamples/mlkit#56]
Hello, 

I found this: 
https://github.com/firebase/quickstart-android/blob/master/mlkit/app/src/main/java/com/google/firebase/samples/apps/mlkit/common/CameraSourcePreview.java

Could you please explain to me why startIfReady() is called in onLayout()?

**Comment by calren** [comment]
I believe the reason startIfReady() is called is to handle the case where the camera isn't ready to show a live preview yet. We don't want the app to crash in that case, so we do a check to catch the exception. Perhaps the method could be better named to startIfCameraIsReady() 😄 . 

I'm going to go ahead and close this issue since I don't think it's a problem with the sample or api itself, but feel free to continue the discussion here!
