### ISSUE TITLE
How do I train a skipping rope dataset when using Pose?

### ISSUE THREAD

**Issue by HiMsszhang** [googlesamples/mlkit#585]
What's your feature request? Please describe.
I make judgments by judging before I take off and when I take off to the highest position, I use the Android case project, but the performance is very poor, and it is almost impossible to count.

Android, IOS or both

**Comment by ai-plays** [comment]
Hi HiMsszhang,

We actually got a rope skipping question during our recent DevFest (not sure if you happen to be that developer :). We discussed internally about this case. The movement of rope skipping is small and there are many variance of rope skipping poses. It is harder to count compared to larger movements like pushup, squat...

Could you clarify your use case a bit more so that we could provide some suggestions?

1. What is your use case? A training app? Or a monitor tool for a rope skipping competition? or something else? Different application has different accuracy requirement and probably different pose variances. 
2. Do you need to measure a specific rope skipping pose? Or all possible poses?  How do you define a valid move? As long as the person skip the rope? As long as the person jumps (even without rope)? Or must use certain poses?
3. When you say the "performance is very poor", could you clarify a bit more? Did it count less or count more? Which position is mis counted (down or up)? etc..

**Comment by HiMsszhang** [comment]
> Hi HiMsszhang,
> 
> We actually got a rope skipping question during our recent DevFest (not sure if you happen to be that developer :). We discussed internally about this case. The movement of rope skipping is small and there are many variance of rope skipping poses. It is harder to count compared to larger movements like pushup, squat...
> 
> Could you clarify your use case a bit more so that we could provide some suggestions?
> 
> 1. What is your use case? A training app? Or a monitor tool for a rope skipping competition? or something else? Different application has different accuracy requirement and probably different pose variances.
First of all thanks for your reply!
1. My case is closer to the training app, but it is not limited to training, and may also be used in competitions in the future.
> 2. Do you need to measure a specific rope skipping pose? Or all possible poses?  How do you define a valid move? As long as the person skip the rope? As long as the person jumps (even without rope)? Or must use certain poses?
2. I tend to prefer a set of training and be able to record all possible poses. I use specific postures to train the jump rope to the highest and the posture when touching the ground to achieve repeat counting, which actually behaves like the effect of the video below.
> 3. When you say the "performance is very poor", could you clarify a bit more? Did it count less or count more? Which position is mis counted (down or up)? etc..
Here are the two poses and actual performance videos I used for training and my training set csv file:


<img width="425" alt="截屏2022-11-10 上午8 43 34" src="https://user-images.githubusercontent.com/49504344/200974401-3fa61eb6-9653-42fe-8b0f-3a51f4307492.png">
<img width="381" alt="截屏2022-11-10 上午8 42 19" src="https://user-images.githubusercontent.com/49504344/200974434-8e8fe9cd-00c1-4873-b89d-7be9c7127123.png">

https://user-images.githubusercontent.com/49504344/200974277-f3d3860f-1d54-4635-adb5-058dccae3fde.mp4
[squat_csvs_out_basic.csv](https://github.com/googlesamples/mlkit/files/9976294/squat_csvs_out_basic.csv)

**Comment by ai-plays** [comment]
Thanks for sharing the video which is helpful to understand the case.

I assume you are following the ML Kit Colab to do the pose classification. That Colab classifies pose without considering the position of the pose. In another word, if you are at 1m height v.s. 0m height, with the same pose, it will be classified as the same pose.   For the video you shared, the person is moving up and down, but with a very similar pose all the time.

Instead of doing fancy pose classification, could you put the camera low and just count how many times feet leave ground?

**Comment by HiMsszhang** [comment]
Thanks for your reply!I will try to use that. What I currently use is: I use the midpoint of the two crotch as the reference point, and each time the coordinates of the current reference point are recorded and counted through an algorithm, but this limitation is very large, for example, moving the camera up and down will also cause count trigger. I haven't been able to think of a good solution yet.
If you have better suggestions, I'd be glad to hear from you.

**Comment by ai-plays** [comment]
So you will need to detect at least positions of two things in order to count up-down movement. One for the position of the person; one for the position of the environment.  The easiest way I can think about is to fix the latter, e.g. putting the phone at a fix point. 

I will close this issue for now as I think there will be a decent amount of experiments you need to do for your specific use case. Hope you find a good solution and feel free to share it here with other developers :)
