### ISSUE TITLE
[Feature request] ViewModel to persist across screen rotation

### ISSUE THREAD

**Issue by justinw-SMC** [googlesamples/mlkit#595]
**What's your feature request? Please describe.**
Persist object detection state across screen rotations as demonstrated in [Android Lifecycles Codelab](https://developer.android.com/codelabs/android-lifecycles#2).

**Mobile environment**
Android

**Additional context**
Note the tracking id is reset across screen rotation. How to make the tracking model persist across screen rotations?

https://user-images.githubusercontent.com/91086628/205361111-457835d9-cbcb-4a65-9c9f-238c8382be71.mp4

**Comment by ai-plays** [comment]
In the demo app, we recreate the detector when rotating the device for keeping the logic simple. 

The tracking algorithm itself relies on the bounding box of the object in the frame. When you rotate, the frame dimension changes significantly, e.g. from WxH to HxW, thus the bounding box coordinates changes significantly, so it is hard to track. 

We don't have a good universal solution for this at the moment.

If this is an important feature for you, I would try the following:
(1) Use the same detector instance instead of re-creating when rotating the device.
(2) Make the preview to be a square, so that WxH and HxW is the same. Therefore, after rotation, it is more likely for the tracker to find the same object at the location from the previous image frame.

If it is not a critical feature, you may want to guide your users to not rotate (or disable rotation) when using your app.
