### ISSUE TITLE
[Bug report] Object Detection (of vision-quickstart) cannot detect anything if another thread exists

### ISSUE THREAD

**Issue by smithlai** [googlesamples/mlkit#611]
**Describe the bug**
Mlkit ObjectDetection doesn't working property if there is any other time-consuming thread working.    

**To Reproduce**
I want to inference multiple models a time, and this is my psudo code  
```kotlin
class ObjectDetectorProcessor(context: Context, options: ObjectDetectorOptionsBase) :
........
    override fun detectInImage(image: InputImage): Task<List<DetectedObject>> {
        1. start 1st model process task
        2. start 2nd model process task
        3. wait all tasks complete
        4. return a new Tak which handles the 2 tasks above
    }
........
```
And here is the code:    
```kotlin
  fun dummyTaskProcess():Task<Int>{
    val taskCompletionSource = TaskCompletionSource<Int>()
    thread(start = true){
      Thread.sleep(300L) 
      taskCompletionSource.setResult(1)
    }
    return taskCompletionSource.task
  }
//  override fun detectInImage(image: InputImage): Task<List<DetectedObject>> {
//    return detector.process(image)
//  }
  override fun detectInImage(image: InputImage): Task<List<DetectedObject>> {
    val taskCompletionSource = TaskCompletionSource<List<DetectedObject>>()
    val taskDummy = dummyTaskProcess()
    val taskOD = detector.process(image)

    var dummyResult:Int? = null
    var detectedResult:List<DetectedObject>? = null
    thread(){
      var taskmap = mutableMapOf<String, Task<Any>>("taskOD" to taskOD as Task<Any>,"taskDummy" to taskDummy as Task<Any>)
      while (taskmap.size > 0){
        val iterator: MutableIterator<Map.Entry<String, Task<Any>>> = taskmap.entries.iterator()
        while (iterator.hasNext()) {
          val entry = iterator.next()
          val k = entry.key
          val t = entry.value
          if (t.isComplete) {
            when (k) {
              "taskOD" -> {
                detectedResult = taskOD?.getResult() // <List<DetectedObject>>
                Log.e("ObjectDetection", "Detected ${detectedResult?.size} objects")
              }
              "taskDummy" -> dummyResult = taskDummy?.getResult() // Int
            }
            iterator.remove()
          }
        }
      }
      taskCompletionSource.setResult(detectedResult)
    }


    return taskCompletionSource.getTask()
  }
```
Example Steps to reproduce the behavior in sample app:
1. Apply the code above to [ObjectDetectorProcessor.kt](https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/kotlin/objectdetector/ObjectDetectorProcessor.kt) (based on commit f26643c9c3e1461cdc1c8af95067d74a10f88904)
2. Launch App
3. choose Kotlin
4. choose CameraXLivePreviewActivity
5. The default selection is Object Detection, nothing will be detected
6. If you reduce the sleep time to less than about 50, the object detection works again

**Expected behavior**
The object detection should works property and detect multiple objects even a new thread is added.

**SDK Info:**
    implementation 'com.google.mlkit:object-detection:17.0.0'

**Smartphone:**
 - Pixel 4 XL
 - Android 13

**Comment by ai-plays** [comment]
This is the expected behavior given the current implementation details. 

_You should not rely on the statement in this paragraph as it is internal implementation and can be changed at any time: in tracking mode, if the detector doesn't receive an image for too long, it will be reset internally, which then needs some re-initialization before start working again.  In most cases, this behavior is fine and help prevent treating unrelated objects as one (the interval is too long, a lot of things could change, the confidence of tracking the object correctly is very low).  But based on your implementation above, it is basically only doing reset for each API call, and not doing real work._

To work around this, you can disable tracking by setting the detector to SINGLE_IMAGE_MODE via setDetectorMode: https://developers.google.com/android/reference/com/google/mlkit/vision/objects/defaults/ObjectDetectorOptions.Builder#setDetectorMode(int)

If you do want the trackingId, maybe consider decoupling the object detector and dummyTask work and keep feeding image to the detector to maintain good tracking (when tracking works, the cost of the detector is very low).
