### ISSUE TITLE
[Feature request] MediaPipe Holistic implementation

### ISSUE THREAD

**Issue by MelsJagt** [googlesamples/mlkit#636]
I am looking for ways to use [MediaPipe Holistic](https://google.github.io/mediapipe/solutions/holistic.html) within the Flutter to develop mobile apps (Android). I have also seen that several MediaPipe solutions/models are made available through [ML Kit](https://developers.google.com/ml-kit/). These models are in fact provided by the [Flutter plugin](https://pub.dev/packages/google_ml_kit), however the list does not include the Holistic model yet. 

I want to build a mobile (Android) app where video images are processed in real time by the model. My question is if there are developments on the deployment of the Holostic model in the plugin, or if there or other suggestions on how the implement the model within flutter for mobile app development  for Android.

**Comment by ai-plays** [comment]
Hi MelsJagt,

In ML Kit, we currently do not have a plan to work on the Holistic SDK.

Two workaround I may consider:
1. See if you can achieve your needs by combining some existing ML Kit features, e.g. Face detection, Pose detection
2. Use MediaPipe Holistic directly by following the instructions on their website https://google.github.io/mediapipe/solutions/holistic.html

BTW, the ML Kit flutter plugin you linked is owned by a developer instead of Google: https://github.com/bharat-biradar/Google-Ml-Kit-plugin  For flutter plugin specific questions, you could considering reaching out in that github repo.
