### ISSUE TITLE
[Bug report] Request for Xcode 15 Beta Support

### ISSUE THREAD

**Issue by FuJianyong** [googlesamples/mlkit#687]
We integrated MLKitTextRecognitionCommon framkwork with pod 'GoogleMLKit/TextRecognition', '3.2.0' in our oc project . But we recently built project with Xcode 15 Beta1, then got such error "clang: error: unable to execute command: Segmentation fault: 11".

**Comment by cldrake01** [comment]
Same here, and I haven't come across a solution.

**Comment by robinmo** [comment]
> Same here, and I haven't come across a solution.

Do u have any workround?

**Comment by robinmo** [comment]
Found solution [xcode 15 linking error](https://developer.apple.com/forums/thread/731089)

**Comment by cldrake01** [comment]
> Found solution [xcode 15 linking error](https://developer.apple.com/forums/thread/731089)

What a Godsend! Thank you.

**Comment by robinmo** [comment]
@calren could u pls help close this issue or assign to the maintain one?

**Comment by calren** [comment]
@miworking Do we have plans to address this one in the near future? Feel free to close if not, or tag someone more appropriate to triage.

**Comment by miworking3** [comment]
I'm afraid we don't have a plan to fix this in the near future, at least in Q3.

**Comment by mrRedSun** [comment]
Why is this closed? Still an issue

**Comment by bmsheppard** [comment]
If there is no plan to fix this in the near future, can we at least get this documented so others don't waste more time figureing out why iOS applications won't build? There is no mention of this on the [ML Kit](https://developers.google.com/ml-kit) home page.

**Comment by robinmo** [comment]
For Xcode15.1 and Xcode15.2, this issue is gone(no longer need to added "-ld64" to "Other linker Flags" ).
It seems Xcode beta issue.

**Comment by miworking3** [comment]
We've recently launched an updated version to ensure compatibility with Xcode 15.1, as detailed in our release notes: https://developers.google.com/ml-kit/release-notes#improvements.

Please test it using Xcode 15.1, and if the issue remains, feel free to reopen this discussion.

Regarding support for Beta versions, currently, we do not have plans to offer this in the near future. Our focus is typically on providing support for official releases rather than Beta versions.
