### ISSUE TITLE
Deploy MLKit Face Detection Models Manually

### ISSUE THREAD

**Issue by andredoubleu** [googlesamples/mlkit#75]
I'm using the MLKit Face Detection SDK for Android to detect the contours of a user's face.

When following this guide (https://developers.google.com/ml-kit/vision/face-detection/android), it shows how developers can (1) bundle the face detection model files within the compiled apk, or (2) download the face detection model files at runtime from Google Play Services.  I'm trying to run this SDK on various embedded devices.  On all of these devices, if I use option (1), the SDK works perfectly.  If I use option (2), on some of my devices, the face detection models never get downloaded.  I've read that the version of Google Play Services on the device can prevent downloads from occurring, but I don't have the ability to update Google Play Services on these devices.

When I use option (1) and compile my apk, I see that MLKit bundles a folder called "models" inside of the assets directory of my apk file. The "models" folder contains a bunch of .tflite, .tfl, .emd, and .pb files.  To get around the files not downloading, I want to deploy "libface_detector_v2_jni.so" and the ".tflite" files on my own.  If I deploy these files myself (say, through my own download mechanism), can I instruct the SDK where to look for them?  Or can I upload these files to Firebase as custom models so I can control the download myself (if I upload these files to Firebase as custom models, which files do I need to upload -- all of them?)

Just to be clear: although I can use option (1) above and it works, I'm trying to keep our apk file as small as possible, and excluding the model files reduces my apk size by ~16 MB.

Thank you!

**Comment by swiyu** [comment]
Currently, we only have these two options in ML Kit. For the Play Service, we are continuously improving the download experience, but there are several reasons that the download may fail, for example, the storage is not enough or as you mentioned, the version is too low. You could try to restart your devices, to see whether it solve the play-service issues. 

Another option is to use App bundle to deliver the face detection feature as a separate module, so that it won't increase your APK size, but will download on-demend. 

Thanks for your suggestions about manual model insert! I will raise it in our internal team discussion.

**Comment by andredoubleu** [comment]
Unfortunately, App Bundles won't work for me since we deploy our app to embedded devices without going through Google Play.

However, thank you for raising the discussion with your team!

**Comment by swiyu** [comment]
Also, the SDK includes 4 architectures for the .so file. If you know what architecture you will deliver, you could reduce the APK size in some extend.

**Comment by andredoubleu** [comment]
@swiyu: Yup, adding abiFilters in my build.gradle file for "armeabi-v7a" and "arm64-v8a" (the only two architectures we support) was one of the first things I did.

**Comment by cs-googler** [comment]
Unfortunately, there is nothing planned to support this currently.
