### ISSUE TITLE
[App Store Blocker] MLKit Dependencies out of Apple Compliance

### ISSUE THREAD

**Issue by zk-zeekay** [googlesamples/mlkit#795]
**Describe the bug**
MLKit's dependency on GoogleToolboxForMac 2.1 is blocking users of MLKit from using GoogleToolboxForMac >=4.2.1, which contains the privacy manifest required by Apple for the following libraries (https://developer.apple.com/support/third-party-SDK-requirements/). 

**To Resolve**
Please update the dependencies of MLKit so that the latest version of GoogleToolboxForMac can be used and users of the MLKit iOS SDK can avoid being blocked from uploading to App Store Connect starting May 1st (https://developer.apple.com/news/?id=3d8a9yyh)

**Comment by miworking3** [comment]
We are working on a new release for this.

**Comment by ArthurAlvarez** [comment]
Any updates on this? I've been receiving some warnings when I upload builds to App Store Connect

**Comment by miworking3** [comment]
We will have a release in April.

**Comment by RogVok** [comment]
Update: looks like GoogleMLKit v 6.0.0 with a new privacy manifest has been released: https://developers.google.com/ml-kit/release-notes 
Thanks, MLKit team!

**Comment by ArthurAlvarez** [comment]
@miworking3 in this new release the pod GoogleMLKit/Translate minimum iOS version was raised from iOS 12.0 to iOS 15.5 which is a blocker for people that must support older iOS versions. Was this done on purpose or is it a misplaced value on the Podspec?

**Comment by miworking3** [comment]
It is for the compliance of privacy manifest: One of Translate's external dependency `SSZipArchive` carries their privacy  manifest in their latest version: `2.5.5`: https://github.com/CocoaPods/Specs/blob/2528d7723aea0c22a357d109d34d5a6a723dc757/Specs/b/8/1/MLKitTranslate/5.0.0/MLKitTranslate.podspec.json#L5

where it upgraded its minimum os version to 15.5: https://github.com/CocoaPods/Specs/blob/master/Specs/2/1/2/SSZipArchive/2.5.5/SSZipArchive.podspec.json#L21
that's why MLKitTranslate have to upgrade minimum os version to `15.5` as well

The same thing happens to `MLKitDigitalInk`, however, will not affect other SDKs, so the overall minimum os version of ML Kit family is still `12.0`, while for Translate and DigitalInk, they require at least `15.5`.
