### ISSUE TITLE
Face Detector working on iOS12 but not on iOS13

### ISSUE THREAD

**Issue by thefabbulus** [googlesamples/mlkit#94]
Since the migration from Firebase MLKit to the new Google MLKit, the FaceDetector is not working great on iOS12 (no faces detected).

Testing the face detector on two devices – same model, iPhone Xr, one with iOS 12.2 and one with iOS 13.5 – gives different results.

More info: https://stackoverflow.com/questions/63114877/new-google-mlkit-facedetection-not-working-on-ios12

**Comment by chrisito** [comment]
Fabrizio, we don't see this internally or with the ML Kit sample app. Can you help to share more information to understand what may be happening? E.g.

1. Is it reproducible on the simulator or real device? The snapshot looks like from a simulator, but needs to confirm.
2. Does it reproduce for you with MLKit's sample app at: [https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision](https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision)
3. If it reproduces with specific faces can you share the image file that is used for face detection?
4. Could you share the Podfile.lock that was generated after pod update? That will contain the version information of the ML Kit's Face Detection API.

Thanks, this info would be helpful for further investigation.

**Comment by miworking3** [comment]
Hey, we may need more information for further investigation because the stackoverflow thread says it doesn't work on iOS12:
https://stackoverflow.com/questions/63114877/new-google-mlkit-facedetection-not-working-on-ios12

**Comment by edritech93** [comment]
same issue for me, I use device iPhone Xr

**Comment by miworking3** [comment]
This problem hasn't been around for over a year, if you see it again, could you provide more info using the following template? Thanks

# Describe the bug A clear and concise description of what the bug is:

# Steps to reproduce the problem in sample app:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error
If applicable, please include code snippet and sample input(image, video, text, etc)

# Expected behavior A clear and concise description of what you expected to happen.

# SDK Info:

# Pod Name & Version [e.g. GoogleMLKit/FaceDetection, 3.0.0]:

# Podfile.lock:

# Device:
## Device/Simulator: [e.g. iPhone6, Pixel 5]
## Device/Simulator OS: [e.g. iOS8.1, Android API 30]
## Development Environment: (For Android issue feel free to skip this section)

# IDE Eversion: [e.g. Xcode 13.1, Android Studio 4.2]
# Laptop/Desktop: [e.g. iMac Pro (2017), HP Z840 Workstation]
# Laptop/Desktop OS/version: [e.g. macOS 12.0.1]
