### ISSUE TITLE
Does the Barcode Scanner support I25(ITF) type for Brazil Boleto? 

### ISSUE THREAD

**Issue by yihanseattle** [googlesamples/mlkit#98]
Can't figure out the reason why we cannot scan I25(ITF) even though ITF is supported in ML Kit. 

Wikipedia Link for Type I25(ITF): 
[I25 Wikipedia](https://en.wikipedia.org/wiki/Interleaved_2_of_5)

Please help if you know the reason if ML Kit support the format or not. And can we use custom model for barcode scanning. 

Example image:
![image](https://user-images.githubusercontent.com/7017516/88991354-4f436b80-d295-11ea-8b15-d4cd8cfe6bfb.png)

I was testing out the Brazil Boleto ticket. You can test the Boleto ticket below:
[Example Boleto](http://www.sicadi.com.br/mhouse/boleto/boleto3.php?numero_banco=341-7&local_pagamento=PAG%C1VEL+EM+QUALQUER+BANCO+AT%C9+O+VENCIMENTO&cedente=Microhouse+Inform%E1tica+S%2FC+Ltda&data_documento=30%2F07%2F2020&numero_documento=DF+00113&especie=&aceite=N&data_processamento=30%2F07%2F2020&uso_banco=&carteira=179&especie_moeda=Real&quantidade=&valor=&vencimento=30%2F07%2F2020&agencia=0049&codigo_cedente=10201-5&meunumero=00010435&valor_documento=260%2C00&instrucoes=Taxa+de+visita+de+suporte%0D%0AAp%F3s+o+vencimento+R%24+0%2C80+ao+dia&mensagem1=&mensagem2=&mensagem3=ATEN%C7%C3O%3A+N%C3O+RECEBER+AP%D3S+15+DIAS+DO+VENCIMENTO&sacado=&Submit=Enviar)

Below is the tool to generate Boleto barcode:
[Boleto Generator](http://www.sicadi.com.br/mhouse/boleto/geraboleto.php)

Thanks so much!

**Comment by zhouyiself** [comment]
Thanks for report!
ITF type is supported. I have tried out the given sample and it can produce the correct result: 034193833200260001790001043510049102015000

Which barcode dependency you use in your build.gradle file?

**Comment by yihanseattle** [comment]
Hi @zhouyiself , thank you so much for the response!

I just tried the [ML Kit quickstart sample](https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart). The default LivePreview didn't work. 

Yes, we also discovered later that it worked if we changed the "Preview Resolution" to 1600 x 1200 or similar in both LivePreview and CameraXLivePreview. 

May I ask how did you test it? What configuration did you use? 

1) Which app and  configuration did you use? (Preview Resolution, Camera or CameraX, etc) Do you recommend auto-focus enabled? 
2) How about low-end Android devices that might not support Preview Resolution of 1600 x 1200? Do we have a recommended minimum Preview Resolution for Android? So we can try to get the highest Preview resolution if possible but not too large at the same time.
3) Do you happen to know that the Brazil Boleto (I-25) type can be scanned if we only use ITF type like below? We don't need to use other types. Does only `Barcode.FORMAT_ITF` instead of `Barcode.FORMAT_ALL_FORMATS` improve the accuracy as well? Trying to get as fast and accurate as possible. 
`barcodeScanner = BarcodeScanning.getClient(new BarcodeScannerOptions.Builder()
                .setBarcodeFormats(Barcode.FORMAT_ITF)
                .build());`

Thanks so much!

**Comment by zhouyiself** [comment]
Thanks for reaching out!

1. Which app and configuration did you use? (Preview Resolution, Camera or CameraX, etc) Do you recommend auto-focus enabled?

I'm also using the quickstart sample app but using StillImageActivity to test the image you posted. You're right that it works partially for this image (w:1024 option works but not w:640). Regarding "auto-focus", I prefer to leave it on.

2. How about low-end Android devices that might not support Preview Resolution of 1600 x 1200? Do we have a recommended minimum Preview Resolution for Android? So we can try to get the highest Preview resolution if possible but not too large at the same time.

There're input image guidelines from the developer page that might helpful.
https://developers.google.com/ml-kit/vision/barcode-scanning/android#input-image-guidelines

3. Do you happen to know that the Brazil Boleto (I-25) type can be scanned if we only use ITF type like below? Does it need to use other types to be scanned successfully? Does only Barcode.FORMAT_ITF instead of Barcode.FORMAT_ALL_FORMATS improve the accuracy as well? Trying to get as fast and accurate as possible.
barcodeScanner = BarcodeScanning.getClient(new BarcodeScannerOptions.Builder().setBarcodeFormats(Barcode.FORMAT_ITF) .build());

If your case only need to support ITF type, Barcode.FORMAT_ITF is better as it won't hurt accuracy but faster.

4. One last question, have you test the fastest and average time to get a success result? We are trying to use it to improve our user experience.

Sorry I didn't do a comprehensive evaluation for this particular type.

**Comment by yihanseattle** [comment]
@zhouyiself 

Thank you so much! That was a big help 👍 

Will let you know if we have further questions :) 

Bests,

Yi
